r-lib/lintr

R/single_quotes_linter.R
tests/testthat/test-single_quotes_linter.R

A legitimate use of a single quote pair in R is to quote a literal double quote. This tiny patch allows this. It's not immediately clear to me how to test a negative with your check_lint tests. Thanks.

permit single quotes if they quote literal double quotes

---

DESCRIPTION
R/lint.R

When running under a version of RStudio that supports the source marker API display lints using the Markers pane (this behavior can be disabled via a global option). Note that this requires the most recent daily build of RStudio (v0.99.206) however will automatically degrade to the previous behavior when running any older version of RStudio. You can download the daily build here: http://www.rstudio.org/download/daily/desktop/

Use RStudio source marker API to display lint items

---

R/commented_code_linter.R
tests/testthat/test-commented_code_linter.R

This linter looks for code-like comments, allowing roxygen blocks which may contain examples.

Add linter for commented R code

---

R/comments.R
tests/testthat/test-comments.R

Currently, the `CI` environment variable is double dereferenced, first in `in_ci` and the result again in `logical_env`. For me, this makes `in_ci` always return `FALSE` and disables commenting. 
This fixes the problem and adds a short unittest.

fix CI environment detection

---

R/spaces_left_parentheses_linter.R
tests/testthat/test-spaces_left_parentheses_linter.R

HI @jimhester, 
I tried to exclude checking `!` before a left parenthesis from `spaces_left_parentheses` in order to pass like `!(a == b)`. Could you review it?
Thanks,
Yu

Exclude checking `!` from spaces_left_parentheses_linter

---

R/spaces_left_parentheses_linter.R
tests/testthat/test-spaces_left_parentheses_linter.R

HI @jimhester,
I think it would be more natural to pass the rule for a space before a left parentheses with `:` and `[` as follows.
```
(x - 1):(y - 1)
x[(x - 1):(y - 1)]
```
Thanks,
Yu

#77 Add ":" and "[" into the rule for a space before a left parentheses

---

README.md

Adds an example image for Atom in a theme that somewhat matches the existing images.
Corrects the link to linter to the actual repository.
If you would prefer this against the `atom` branch just let me know.

Add an example image for Atom

---

R/commas_linter.R
R/get_source_expressions.R
tests/testthat/test-commas_linter.R

This is related to #111. It looks like the root cause is that when there is empty line(s), the parsed results' row number (id) is different from line number, which is provided in the `names`.
I also find it more intuitive for the missing space after lint to have position to be after comma so it is as easy as to press space to take the advice in RStudio for example. Hope you are okay with this change and me jamming it in this PR.

Get correct line_number in commas_linter

---

R/cache.R
R/exclude.R
R/get_source_expressions.R
R/methods.R
R/spaces_left_parentheses_linter.R
R/trailing_blank_lines_linter.R
R/zzz.R
tests/testthat/test-spaces_left_parentheses_linter.R

Currently `spaces_left_parentheses_linter` contains false negatives when it comes to
```r
for(i in seq_along(1:10)) { }
```
where `if`, `for`, `while` blocks could contain function calls.
It seems to me that we can improve this linter by stricter checking on the type of `(`'s owner. Previously if the line has any function calls, we completely let it go.
I have also incorporated the improved linter's suggestions in this PR. Hope that is okay.
Finally I'm not very familiar with this package yet. So definitely let me know if you see any concerns or potential improvements of my PR.

Make spaces_left_parentheses_linter more robust when determining `(` type 

---

R/absolute_paths_linter.R
R/cache.R
R/comments.R
R/expect_lint.R
R/get_source_expressions.R
R/infix_spaces_linter.R
R/lint.R
R/object_usage_linter.R
R/objects_linter.R
R/settings.R
R/tree-utils.R
R/utils.R
tests/testthat/test-commented_code_linter.R
tests/testthat/test-comments.R
tests/testthat/test-exclusions.R
tests/testthat/test-infix_spaces_linter.R
tests/testthat/test-knitr_formats.R

If I'm not mistaken, according to the style guide and your current code implementation, `=` is meant to be linted. However it seems that `=` inside function calls is a differently named token versus plain `=` assignment. I have added `EQ_SUB` to the list to capture that.
In addition, `=` inside function calls treats the entire function call as its parent. Therefore I changed the siblings check to be "greater than one" rather than "equal to two". If I understand your intention correctly, this check is meant to prevent false positive like `-1, <2` etc. So far I haven't been able to come up or find any false positives my change would introduce.
Let me know if I missed anything or incorrectly interpreted the style guide.

infix_spaces_linter should check `=` inside function calls

---

DESCRIPTION
NEWS.md
R/get_source_expressions.R
R/tree-utils.R

It is also faster, at least the complicated QC.R case. I also profiled it for this file, it is as fast as it gets, `self.time: 0.00`, `self.pct: 0.00`. :)

Replace igraph calls with our own R code, get rid of igraph

---

NEWS.md
R/lint.R

Hi Jim,
when turning on the cache flag, I wasn't getting any speed improvements.  With this pull request, files are being saved and compute much faster.
(on the GGally package...)
```{r}
load_all("../../../lintr/lintr/"); 
system.time({lint_package(cache = TRUE)})
system.time({lint_package(cache = TRUE)})
```
Best,
Barret

fix cache logic

---

DESCRIPTION
NEWS.md
R/get_source_expressions.R

As discussed at https://github.com/jimhester/lintr/issues/153
I had to temporarily add `Remotes`, the CRAN version is somewhat buggy. It pretty much only comes out in lintr. :( I'll submit a new version to CRAN next week, maybe we'll find other issues.
I'll add it to the NEWS after I'll have a PR id.
I'll also submit another PR that uses this feature in minute.

Parsed data in XML via xmlparsedata

---

R/seq_linter.R
tests/testthat/test-seq_linter.R

Some fixes for the new seq_linter:
* Find `1L:length(...)`, etc. expressions as well.
* Proper printout for the `length(...):1` expressions. Somewhat surprisingly, these are found, too, there is no order in the XPath search.

seq_linter fixes: 1L:length(...) and length(...):1

---

R/comments.R

This is a fix for #171. `httr::http_condition` was called with wrong arguments leading to an error.

Correct call signature for http_condition.

---

README.md

Syntastic expects a list of strings here. The current proposed settings leads to the error:
syntastic: error: variable g:syntastic_r_checkers has to be a list of strings

Fix for syntastic error in VIM

---

R/line_length_linter.R
tests/testthat/test-line_length_linter.R

While other linters' messages start with upper case characters (as they are full sentences), `line_length_linter` prints a message starting with a lower case character.
This patch adjusts `line_length_linter` accordingly.

Fix case for line_length_linter message

---

NEWS.md
R/extract.R
R/get_source_expressions.R
R/lint.R
R/no_tab_linter.R
man/Lint.Rd
tests/testthat/test-get_source_expressions.R
tests/testthat/test-no_tab_linter.R

Hi Jim,
Please have a look at this PR which adds proper handling for tab character in source code. As you know, the R parser expands tab characters into a variable number of space characters (for 8-character wide indentation). This PR fixes the column numbers in the parsed_content table.
This is a change to a central piece of code, hence the PR. I have added various tests for this and the complete test suite passes successfully.
Cheers,
Florent

Tab correction

---

README.md

First PR so let me know if i'm doing it wrong - simply fixing a link in the README to the Debian control fields docs.

fix debian control fields link

---

DESCRIPTION
NEWS.md
R/addins.R
README.md
inst/rstudio/addins.dcf

This commit adds two addins to RStudio to bind shortcuts for easier usage. Now you can, for example, bind
Alt+Shift+L and lint the current source code.

Adds RStudio addins

---

R/addins.R

closes #280 (missing config file for using RStudio add-in to `Lint current file`)

fixing bug with missing config file

---

NEWS.md
R/lint.R

For my project, I have a lot of httptest cache files that should not be linted. While I can add them to the exclusions, the current implementation reads in the files before excluding, causing linting to take 30+ min.
This change removes fully excluded files as early as possible to avoid reading them in.

For fully ignored files, remove from `lint_package` prior to any further processing.

---

NEWS.md
R/spaces_left_parentheses_linter.R

There were failing tests beforehand. These are unrelated.

fix: Allow for (( when linting. Fixes #259

---

README.md

The current documentation led to errors in Sublime Text 3. Also, it was challenging to find how to disable certain linters, so I included that in the example too.

Update Sublime Text configuration section of README

---

R/settings.R

This lets users specify the location of the linter file with
options(lintr.linter_file) before calling lintr::lint(). This should
be useful to allow the various plugins to specify the path to the
.lintr file
Related to #123 and #335

Allow users to set lintr.linter_file

---

NEWS.md
R/object_name_linters.R
tests/testthat/test-object_name_linter.R

Fixes #341. Example usage: ` lint("inst/example/bad.R", object_name_linter(c("dotted.case", "lowerCamelCase"))`

Allow passing multiple styles to object_name_linter

---

NEWS.md
R/extract.R
tests/testthat/knitr_formats/test.Rmd

Rmarkdown format allows the use of code blocks in the following format
~~~~
```{some_engine}
foo = bar
```
~~~~
These blocks should be filtered out before linting the remaining R-code blocks.
A couple of python blocks were added to test.Rmd: one with R-like syntax and one with syntax that can't be parsed as R.
The function `defines_knitr_engine` was extracted from `extract_r_source` and extended. This tests for the presence of {r engine = some_engine} and {some_engine} in the start line of a code chunk. The names of valid engines are obtained from `knitr::knit_engines`
An unrelated, cosmetic change to `filter_chunk_end_positions` was made (which(grepl(...)) --> grep(...)).

fixes #322: allows Rmd chunks using {lang} engine format

---

tests/testthat/checkstyle.xml

Mismatching `lintr` versions between the earlier version of the changed file and `checkstyle_output()` threw a testthat error. Ref https://github.com/jimhester/lintr/issues/363

bump `lintr` version in checkstyle

---

README.md

Looks like this was added in https://github.com/jimhester/lintr/pull/83 but not added to documentation

Add `commented_code_linter` to documentation of possible linters

---

R/object_name_linters.R

As described in #226 , the speed of the `object_name_...` linters has reduced since introduction of the `object_name_linter("snake_case")` style linters
The function `make_object_linter` was refactored. Some conditional logic, that checked whether a given object was an operator, a generic or a base-function and bypassed that object if it was, was moved out of an lapply loop into a prefiltering step. This step is vectorised over all object-names in a given file, so speeds up linters that are built using `make_object_linter`.
No additional unit-tests were added
For analysis of the `check.R` file referenced in #318  using a) the CRAN version (1.0.2); b) the current master github version; c) the updated version
code:
```
system.time(lint("helpers/check.R", linters = object_length_linter(20), …
```

speed up make_object_linter - ref issue #226

---

DESCRIPTION
NEWS.md
R/exclude.R
R/utils.R

The dev version of `xmlparsedata` has been updated to fix a parsing bug on R-3.6; before fixing that bug several lintr tests were failing (https://github.com/jimhester/lintr/issues/384). This change points `lintr` to the dev version of xmlparsedata

ensure lintr runs/installs/tests on R-3.6

---

DESCRIPTION
R/object_name_linters.R
man/linters.Rd
tests/testthat/test-object_name_linter.R

Previous xml-based version of `object_name_linter`:
- required all names to match every one of the requested
styles
- disregarded names of formals in newly-defined functions
Hence:
- added extra xpath clause to catch `SYMBOL_FORMALS`
- used or-reduction to ensure each name matches at least one
style.
Also:
- since multiple styles are allowed, the lint message is now
like "Variable and function name style should be style_1,
style_2 or style_3".
- tests for `object_name_linter` and lint message for
`object_name_linter_old` were changed to match this
format.
- added `...` argument to a unit test to ensure that
`object_name_linter` does not flag dots.

lint formals and ensure names match >= 1 style

---

.Rbuildignore
.covrignore
.travis.yml
DESCRIPTION
codecov.yml
cran-comments.md
tests/testthat/test-REMOVE_THIS_TEST.R

add matrix of travis R releases (3.2 -> devel)
Used `use_tidy_ci()` to expand the R-releases used during CI tests
- add configs for codecov
- bump R dependency to R >= 3.2 (since 3.2 is the earliest release
used in CI; also dependency httr/knitr require R >= 3.2)
- `use_tidy_ci` modified `cran-comments.md`; I changed the file
so that R 3.1 wasnt mentioned in the travis section. But, I dont
really know what is supposed to go in this file.
Note that I've added a failing test just to check that CI fails for all builds before pushing to lintr master

Check on multiple r releases

---

README.md

Fixes #399. Adds missing linters to the README, and updates the list of object naming styles for `object_name_linter()`.

Update list of linters in README

---

DESCRIPTION

`expect_lint_free` uses testthat::skip_on_covr, which was not introduced into testthat until 2.2.1
https://github.com/jimhester/lintr/blob/38279839efe0f685b281e80a77bcea1b04665f33/R/expect_lint.R#L110

Set testthat dependency to 2.2.1

---

R/function_left_parentheses.R
tests/testthat/default_linter_testcode.R
tests/testthat/test-defaults.R
vignettes/creating_linters.Rmd

When Lint() finds a lint, the name of the 'linter' responsible
(ie, the 'linter' argument to Lint()) should match the name of the linting function.
For `function_left_parentheses_linter` this was not the case and this
mismatch has now been fixed
For all other linting functions, the reported linter name matches the
function name.
A test was added to ensure that the 'linter' field reported by lint() matches the linting-function's name for each default linter (happy to remove if you think this might become a flaky test).
The 'linter' argument to Lint() was added to the `assignment_linter` example in the vignette.

fix #426 : match the 'linter' argument in Lint() to the function name

---

NEWS.md
R/object_usage_linter.R
tests/testthat/test-knitr_formats.R
tests/testthat/test-object_usage_linter.R

In #432 it was noted that the line-number for object-usage-linter
warnings were often incorrect. They were being reported relative to the
start of the defining function, rather than the start of the file.
- A test was added that throws an object-usage-lint on line-2 of the
function but line-5 of the file.
- Modified object-usage-linter.R so that it reported the line-number from the original file, rather than the line-number of the encasing function
This led to several of the knitr-format tests failing because lints were throwing in a different order. The original tests were misordered , and have been modified.
Briefly: 
Each of the knitr-format tests had code blocks that look like this:
~~~~
a = 1
~~~~
~~~~
b <- function(x) {
d = 1
}
~~~~
The lints should be ordered:
- assignment (`=` for …

fix #432 - Object usage line numbers

---

NEWS.md
R/path_linters.R
R/utils.R
tests/testthat/helper.R
tests/testthat/test-absolute_path_linter.R
tests/testthat/test-nonportable_path_linter.R

In issue #433 , filepaths that were surrounded with double-quotes were immune to the absolute-path-linter. This issue also affected the nonportable path linter.
Here, 
- some tests were added to ensure that double-quoted filepaths are linted by the path-linters.
- `absolute_path_linter` and `nonportable_path_linter` were refactored to place any duplicated logic in a function-builder (`make_path_linter`)
- strings that are surrounded by double (single, respectively) quotes were stripped of the surrounding double quotes and then the remaining double quotes were unescaped
- (outdated; unquote has not been modified) The latter change was achieved by modifying `unquote` to accept a vector of quote-characters;
- The change was achieved by getting the path-linter to select the appropriate …

fix #433 : Double quotes in path linters

---

NEWS.md
R/get_source_expressions.R

The parsed_content generated in R-devel (to be R4.0) uses a token `expr_or_assign_or_help` in the same way that R3.6 used `equal_assign`. Parsing code with equals-assignments caused problems when running lintr on R-devel for this repo (see #403 ): https://github.com/csgillespie/poweRlaw/commit/ede33811f79376cb0a4ca29f8b0972a8b8b35910 
The existing `lintr` code had a function `fix_eq_assigns` that handled `equal_assign`; this PR just extends that code to handle `expr_or_assign_or_help` in the same way.
To work out what was going on, I extracted the contents of an lapply loop(in `get_source_expressions`) into a stand-alone function `get_single_source_expression` to aid debugging.

Fix the parsing of source-expressions on R-devel

---

NEWS.md
R/single_quotes_linter.R
tests/testthat/test-single_quotes_linter.R

fixed an issue that caused a
Error in rep.int(character, length) : invalid 'times' value
that caused an issue when printing results from the single_quotes_lintr
It was assumed in highlight_string that the range was such that
range[1] < range[2] which is not necessarily the case when
the string is split over a new line. Added a test case for this
too.

lintr:::print.lint issue

---

R/get_source_expressions.R
tests/testthat/test-commas_linter.R
tests/testthat/test-error.R

Closes #461 
This PR fixes the handling of source code such as 
```r
x=
```
```r
sum(1:10, na.rm += 1)
```
for which the parse data stops at the `=` in these cases where the last token is always `EQ_ASSIGN`. This PR adds a condition that if the last token is `EQ_ASSIGN` then `fix_eq_assigns` should not do anything because `next_with_parent` no longer works.

Fix fix_eq_assigns with last token being EQ_ASSIGN

---

DESCRIPTION
NEWS.md
R/extract.R
man/default_linters.Rd
man/default_settings.Rd
man/default_undesirable_functions.Rd
tests/testthat/checkstyle.xml
tests/testthat/knitr_formats/test.Rmd
tests/testthat/knitr_malformed/incomplete_r_block.Rmd
tests/testthat/test-knitr_formats.R

See #472  lintr was complaining that files were malformed when containing
unevaluated code-blocks of the following form (cpp is a format specifier
for use by markdown).
~~~~
```cpp
blah
```
~~~~
~~~~
"```" matches the end-block pattern for Rmd-code blocks; the change
allows the start pattern for unevaluated blocks to be "```" or
"```some_language"
~~~~
A couple of such blocks were added to the .Rmd used in the knitr-format
test.
`extract_r_source` has been refactored: selection of start / end
positions for each code block is handled by `get_chunk_positions`.
Also
- bumped the lintr version from 2.0.1 to 2.0.1.9000
- refactored some knitr-format tests that had some regex-definition duplication
- added a malformed .Rmd containing an incomplete R code block to the tests
- pushed some man/ …
```

Fix #472: Allow non-evaluated code blocks with markdown format-specifier

---

NEWS.md
R/object_name_linters.R
README.md
tests/testthat/test-object_name_linter.R

I like to write variables in snake_case except when they are CONSTANTS.
To prevent the `object_name_linter` from complaining, I would like to allow (uppercase) "SNAKE_CASE" as an option.

Add SNAKE_CASE style option

---

NEWS.md
R/cache.R

This should fix #60. As discussed in the links from that issue, by
default ESS turns on caching, which causes lintr to try to create a
subdirectory inside of ~/.R. However, if ~/.R doesn't exist in the
first place, dir.create will fail and lintr will not work in emacs. By
adding the recursive = TRUE argument to dir.create, this will now
create all parent directories as necessary to create the desired cache.
After this (very tiny) fix, the `testthat` suite succeeds (provided `mockery` is available. 
To test whether this addresses the issue in emacs, I've used vagrant to create a clean Ubuntu 20.04 VM, installed emacs and r, installed some lintr dependencies with apt, then used devtools to install from my github fork. I then configured ESS and confirmed that linting now works! I previously …

recursively create cache directory

---

NEWS.md
R/methods.R

print RStudio source markers for empty lints

---

R/exclude.R

A user seeing this may not have called `lintr` directly (e.g. it's part of a suite of checks), so specifically calling out that it's related to linting will be helpful.
Also wanted to get the pluralization right, and specifically referring to "ranges" is a further clarification.
I think `covr` has a similar sequence, I will file there shortly.

clarify mismatched start/stop exclusion

---

NEWS.md
R/get_source_expressions.R
R/missing_package_linter.R
R/namespace_linter.R
R/seq_linter.R
tests/testthat/test-error.R

Closes #559 
Since lintr might pass a partial or invalid parse data to `xmlparsedata::xml_parse_data`, it could also generate invalid XML text, which also causes `xml2::read_xml()` to fail.
This PR adds a `tryCatch()` to all `xml2::read_xml(xmlparsedata::xml_parse_data(pc))` so that invalid XML text would not cause `lintr::lint` to fail.
Note that all linters that uses the `source_file$xml_parsed_content` must check if it is `NULL` before querying it. This PR adds such checks to `seq_linter`, `missing_package_linter` and `namespace_linter`.

Allow invalid xml

---

R/get_source_expressions.R
man/get_source_expressions.Rd
tests/testthat/test-get_source_expressions.R

Closes #542 
Comment wanted:
1. I documented `get_source_expressions` return object pretty thoroughly. Should this be filed as a separate PR perhaps? Also please have a look to be sure it makes sense, I wasn't totally clear on what all of the components are. If it's good to include in this PR I'll `document()` it.
2. I didn't include the linter in this PR, the thinking is to file a separate issue & PR as a follow-up. Happy to write it here as well.
3. I didn't touch the `readLine` usages in R/exclude.R and R/cache.R. I can look into that as needed.

get_source_expressions detects terminal newlines

---

NEWS.md
R/get_source_expressions.R
tests/testthat/test-error.R

Closes #566.
This PR checks if the parse error message has a hint for the source code error and fixes the handling of `attempt to use zero-length variable name` error caused by empty variable names in the following cases:
```r
``
``()
''()
""()
fun(''=42)
fun(""=42)
fun(a=1,""=42)
```
When this error occurs, it searches the source code with a pattern that covers the above cases.

Fix handling zero-length variable name error

---

R/missing_argument_linter.R
R/missing_package_linter.R
R/namespace_linter.R
tests/testthat/test-missing_argument_linter.R
tests/testthat/test-missing_package_linter.R
tests/testthat/test-namespace_linter.R

This PR changes the following linters based on XML parse data so that they only work with full parse data:
* `missing_package_linter`
* `namespace_linter`
* `missing_argument_linter`
and `file_lines` is used instead of `lines` which was incorrect (missing `line` in results).

Only checks with full parse data

---

R/cyclocomp_linter.R
R/get_source_expressions.R
R/object_name_linters.R
R/object_usage_linter.R
R/semicolon_terminator_linter.R
R/undesirable_operator_linter.R

Part of #584 
I applied several linters across R/ here:
- `commas_linter`
- `trailing_blank_lines_linter`
- `spaces_left_parentheses_linter`
- `object_usage_linter`
- `function_left_parentheses_linter`
- `paren_brace_linter`
I skipped `equals_na_linter` which only gives a spurious match that would be fixed by #546. Similarly there's a spurious instance of `paren_brace_linter` that applies to it's own source where `"){"` is present. We should move that linter to match on the parse tree as well.

apply some linters to R/

---

R/get_source_expressions.R
R/lint.R
R/missing_argument_linter.R
R/missing_package_linter.R
R/namespace_linter.R
R/object_name_linters.R
R/object_usage_linter.R
R/seq_linter.R
R/sprintf_linter.R
R/utils.R
tests/testthat/default_linter_testcode.R
tests/testthat/dummy_packages/package/R/default_linter_testcode.R
tests/testthat/dummy_packages/package/data-raw/default_linter_testcode.R
tests/testthat/dummy_packages/package/inst/data-raw/default_linter_testcode.R

Closes #608 
Renaming entailed fixing some logic that relied on the name being `xml_parsed_content`. In every case I think the new code is cleaner.
Also tidied a few things in the midst of fixing tests that were breaking:
- line width lint applied to `get_assignment_symbols` and `get_function_assignments` in `object_usage_linter`
- `global_parsed_content` in `utils` is unused. Also, it's wrong (it should be `source_file$full_parsed_content`), so I just deleted it.
- minor typo in some test files: `someComplicatedFunctionWithALongCameCaseName` -> `someComplicatedFunctionWithALongCamelCaseName`
TODO:
tested both CRAN & GitHub master:
```
install.packages('goodpractice')
tools::testInstalledPackage('goodpractice')
remotes::install_github("MangoTheCat/goodpractice") …
```

Rename xml_parsed_content for the full file

---

.lintr

Closes #602 
We are already compliant; turning on in `.lintr`

enable object_usage_linter

---

.lintr
R/expect_lint.R
R/get_source_expressions.R
R/spaces_inside_linter.R
R/unneeded_concatenation_linter.R

Closes #596
There are already no lints for this linter, we just need to enable it in the options:
```
lintr::lint_package(linters = lintr::open_curly_linter)
```

enable open_curly_linter in .lintr

---

NEWS.md
R/object_name_linters.R
R/zzz.R

Also remove relevant # nolint in lintrs own .onLoad.
fixes #500

Allow .onLoad and other special functions regardless of name style

---

.lintr
R/get_source_expressions.R
R/utils.R

Closes #595 
in utils.R it's "code-code" whereas in get_source_expressions.R it is only incidentally code (treating `->` as right assignment).
In both cases I used `-->` (which doesn't parse as code), not sure if this is ideal for the utils.R case.

enable commend_code_linter and apply it

---

R/expect_lint.R
R/lint.R
R/methods.R
tests/testthat/test-methods.R
tests/testthat/test-rstudio_markers.R

~(#589 should be merged first)~ *done*
Thanks to @jimhester I now know it's possible to provide to-be-linted source directly to `lint()` by passing a string with a newline.
But printing the resulting lints doesn't work in RStudio, because there's no underlying source file. It looks something like this:
```
> library(lintr)
> linter <- undesirable_function_linter(fun = c("dir" = NA))
> lintr::lint('dir(".")\n', linter)
Error in .rs.normalizePath(marker$file, mustWork = TRUE) : 
path[1]="<text>": No such file or directory
```
whereas this is what you see outside the IDE:
```
library(lintr)
linter <- undesirable_function_linter(fun = c("dir" = NA))
lint('dir(".")\n', linter)
#> <text>:1:1: warning: Function "dir" is undesirable.
#> dir(".")
#> ^~~
```
This PR makes lint printing work in …

Make inline data work in RStudio

---

R/actions.R

Closes #558
Reports the linting via a GHA annotation (a warning) but also puts file and line details into the log

Change reporting of lints in GHA

---

.github/workflows/lint-changed-files.yaml
.lintr_new
NEWS.md

closes #641 
still to-do:
```
linters: with_defaults(
line_length_linter = line_length_linter(120),
T_and_F_symbol_linter = T_and_F_symbol_linter
)
exclusions: list(
"tests/testthat/dummy_packages",
"tests/testthat/knitr_formats",
"tests/testthat/knitr_malformed",
"inst",
"vignettes"
)
```

added lint-changed-files CI workflow

---

tests/testthat/test-error.R

Currently, CI builds on r-devel are failing because the parser error message for input `\` changed from "unexpected input" to "unexpected end of line".

permit new error message (R-devel)

---

R/utils.R
tests/testthat/test-settings.R

One line is uncovered, it's unreachable currently. The `xml_nodes_to_lint` helper only applies to `equals_na_linter`, which always matches the node with `==` or `!=`, which can't be split over multiple lines.
In the future this helper could apply to linters where the line split is possible, so I'll leave it as uncovered for now (no need for `# nocov`, and I don't see a need to use `:::` to test it directly if we can avoid it)

Coverage for utils.R

---

.lintr
tests/testthat/test-T_and_F_symbol_linter.R
tests/testthat/test-absolute_path_linter.R
tests/testthat/test-error.R
tests/testthat/test-exclusions.R
tests/testthat/test-extraction_operator_linter.R
tests/testthat/test-get_source_expressions.R
tests/testthat/test-implicit_integer_linter.R
tests/testthat/test-nonportable_path_linter.R
tests/testthat/test-object_name_linter.R
tests/testthat/test-pipe_continuation_linter.R
tests/testthat/test-semicolon_terminator_linter.R
tests/testthat/test-settings.R
tests/testthat/test-todo_comment_linter.R
tests/testthat/test-undesirable_function_linter.R
tests/testthat/test-undesirable_operator_linter.R
tests/testthat/test-unneeded_concatenation_linter.R

Unfortunately, some newly enabled linters had hits in `tests`, so we aren't lint-free on master atm.

fix delint conflicts

---

NEWS.md
R/lint.R

Demos are typically R code, so should be linted.

Include "demo" directory in `lint_package`

---

R/lint.R
man/lint_dir.Rd
man/lint_file.Rd
man/lint_package.Rd

Fixes #712 and #474
Add description of use of inline R code in the filename argument of `lint()`

Docs: inline code for lint function

---

.lintr

Fixes #603
No lints were observed with `paren_brace_linter` on the code base.

enable `paren_brace_linter` for {lintr}

---

R/closed_curly_linter.R
tests/testthat/test-closed_curly_linter.R

Fixes a plurality typo in the lint message for closed-curly linter (and in the tests for the same).
Previously it said "Closed curly braces should [blah] unless it's followed by ..."
Now it says "Closed curly braces should [blah] unless they are followed by ..."
Also, some pre-emptive refactoring of closed-curly linter prior to addressing it's cyclomatic complexity (to be a separate PR):
- changed indentation to 2-spaces
- reduced duplication in use of "source_file$parsed_content"
- reduced duplication of `rex(the-closed-curly-linter-message)` across the tests for closed-curly-linter

Closed-curly typo

---

R/zzz.R
man/default_linters.Rd

Fixes #510
Appends the names of the default-linters to the manpage for `default_linters`.

docs: add linter-names to ?default_linters

---

NEWS.md
R/lint.R
man/lint_dir.Rd

Ignore `renv` and `packrat` by default in lint_dir

---

NEWS.md
R/comment_linters.R
tests/testthat/test-commented_code_linter.R

Skip commented_code_linter if actual parsed content was matched.

---

R/get_source_expressions.R
R/open_curly_linter.R
tests/testthat/test-deprecated.R
tests/testthat/test-rstudio_markers.R

Closes #672.
Three specific `# nolint`s remain in the source:
```
./R/T_and_F_symbol_linter.R:T_and_F_symbol_linter <- function(source_file) { # nolint: object_name_linter.
./R/lint.R:Lint <- function(filename, line_number = 1L, column_number = 1L, # nolint: object_name_linter.
./R/function_left_parentheses.R:function_left_parentheses_linter <- function(source_file) { # nolint: object_length_linter.
```

Remove spurious # nolints

---

NEWS.md
R/paren_brace_linter.R
tests/testthat/test-paren_brace_linter.R

Anchor to opening brace instead of closing paren in paren_brace_linter

---

.Rbuildignore
R/lint.R

* Use `pattern = NULL` in `lint_package()` fixes #631
* Update `.Rbuildignore` to reflect recent changes:
- added `.lintr_new`
- moved ignore for `tests/testthat/package/.Rbuildignore` to  
new location `tests/testthat/dummy_packages/package/.Rbuildignore`
- added `.idea` (IntelliJ Project Metadata)

Fix R CMD check NOTEs

---

NEWS.md
R/exclude.R
R/trailing_blank_lines_linter.R
tests/testthat/test-trailing_blank_lines_linter.R

I had to fix `parse_exclusions()` as well because the `readLines()` used there didn't muffle the incomplete final line lint.
fixes #675

add trailing_blank_lines lint at end of file if terminal_newline is missing

---

tests/testthat/test-dir_linters.R

Fixed warnings that were produced when running test-dir_linters.
These stemmed from using `assignment_linter` rather than
`assignment_linter()`.

fix warnings in test-dir_linters.R

---

man/linters.Rd

https://github.com/jimhester/lintr/commit/297f959a956c45f77ea74441fda386da2e02e286 changed the roxygen for `assignment_linter` but did not update `man/`
This PR just updates `man/linters.Rd`.

document() recent change to 'assignment_linter'

---

R/comment_linters.R
tests/testthat/test-commented_code_linter.R

fixes #742
the XPath based code_candidates have one row per comment node, not one row per line

use correct index for rows of `code_candidates`

---

.lintr
R/lint.R

Following https://github.com/jimhester/lintr/commit/af6ec3078aeefe8aeeaf76958280199e03319406 the cyclomatic complexity of lint() went up to 34. Since we have two linting steps in the PR review process, this increase in cyclomatic complexity would have been easy to overlook at the time.
The current changes brings cyclomatic-complexity of lint() down to 28 (which is now the threshold set in .lintr), and cleans up the lint function a tiny bit.
The code for defining the set of linters used inside lint(), and for checking that they are all Linter objects has been extracted into helper functions.
I'm attempting to make other changes to lint(); but think the changes here should be included first.
All non-exported helper functions that are in lint.R have been pushed to the bottom of the file for …

Define and validate linters

---

tests/testthat/test-lint_file.R

expect_warning and expect_error with fixed expectations need `regexp = "bla", fixed = TRUE`, not `fixed = "bla"`.
Thanks @MichaelChirico for pointing this out.

fix expectations in test-lint_file.R

---

tests/testthat/test-cache.R

Much of the data used in the tests for 'retrieve_lint' was duplicated across tests.
Added a fixture within the 'test-cache.R' context to set up this data.
This will be useful if we introduce a class to handle cacheing logic (re https://github.com/jimhester/lintr/pull/747)

Add cache-test fixtures

---

NEWS.md
R/T_and_F_symbol_linter.R
R/utils.R
tests/testthat/test-T_and_F_symbol_linter.R
tests/testthat/test-exclusions.R

fixes #657
Migrating to XPath makes adding other exceptions easier as well.
Had to add the argument `offset` to `xml_nodes_to_lint` to keep the column numbers unchanged.

Use XPath for T_and_F_symbol_linter and fix false positives

---

NEWS.md
R/aaa.R
R/object_usage_linter.R
R/pipe_continuation_linter.R
R/spaces_left_parentheses_linter.R
tests/testthat/test-object_usage_linter.R

Correctly parse checkUsage when a multiline warning is encountered

---

.dev/compare_branches.R

Two main new features in this PR:
1. Copy the repo to a temp dir & run the script from there. That way you can continue editing while running, as well as running multiple comparisons at once
2. Given how common it is to skip a package due to installation reasons, etc, move to a flow where we try to accumulate `sample_size` successful lints, as opposed `sample_size` total iterations, some percentage of which are just skipped

Extend branch comparison script

---

NEWS.md
R/object_name_linters.R
tests/testthat/test-object_name_linter.R

Ignore symbols used for subsetting in `object_name_linter`

---

.dev/compare_branches.R

Not an ideal benchmark, but with enough packages included this should give an idea of whether the linter is performing wildly differently between the branches

include execution timing in branch comparison

---

DESCRIPTION
NEWS.md
R/pipe_call_linter.R
tests/testthat/test-pipe_call_linter.R

This enforces the following section of the tidyverse style guide:
https://style.tidyverse.org/pipes.html#no-arguments

New pipe_call_linter enforcing calls (not symbols) in magrittr pipes

---

R/cache.R
R/lint.R
tests/testthat/test-cache.R

Closes #800 
If `find_new_line()` returns `NA` it means the content no longer matches the line, then the cached lints are dropped.

Fix nolint cache

---

R/addins.R

Fixes #788
This PR updates the regex in the `addin_lint()` function to also remove the comments that can be included in the linters section of a .lintr file.
This is a possible fix for #788.

[WIP] Change regex in addin_lint function to also remove comments

---

tests/testthat/test-pipe_call_linter.R

fix https://github.com/jimhester/lintr/issues/812 (the lintr-specific warnings at least)
Formerly, tests for the pipe-call linter used unevaluated function name
`pipe_call_linter` and threw warnings when running tests.
These have all been changed to use `pipe_call_linter()`

fix test warnings: use pipe_call_linter()

---

NEWS.md
R/get_source_expressions.R
tests/testthat/test-get_source_expressions.R

Fixes fail obtained when a syntax error interrupts the parsing at a
Unicode character and, as a consequence, the parsed content returned
by `getParseData(source_file)` includes a truncated UTF-8 multibyte
representation of that character (which is invalid). See the GitHub
issue discussion (#815) for details.
The proposed solution merely "coerces" the `getParseData`'s `text`
column to what it is supposed to be according to its documentation.
An alternative would be to actually fix the table before use:
```r
content[!content$terminal, "text"] <- ""
```

Fix #815 - "error: unexpected input" from unicode character token

---

README.md

[vscode-r-lsp](https://github.com/REditorSupport/vscode-r-lsp) has been integrated into [vscode-R](https://github.com/REditorSupport/vscode-R).
This PR updates the README accordingly.

Update VS Code linting in README

---

.github/workflows/R-CMD-check.yaml

closes #858 
summary: ubuntu-16.04 is deprecated which results in pipeline failures. this PR solves that by moving to ubuntu 18.04 and 20.04. it also makes use of {pak} to speed up dependency installations.

replaced ubuntu 16.04 with 18.04 and 20.04

---

NEWS.md
R/undesirable_function_linter.R
R/utils.R
tests/testthat/test-undesirable_function_linter.R

Closes #866
The issue is that `source_file$lines[[line]]` relies on `source_file$lines` having the line numbers as names, not as integers. So `source_file$lines[['111']]` (correct) is not the same as `source_file$lines[[111L]]` (on HEAD).
This only shows up if the expression at fault comes later in the file (or perhaps just at the 2nd expression of a 2-line file); that's reflected in the new test.
I also tidied up the xpath a bit, I think it's clearer to understand now.
I'll file a follow-up PR using the new helper a bit more broadly.

fix undesirable_function_linter when linted expression is found late in file

---

R/cyclocomp_linter.R
R/expect_lint.R
man/linters.Rd

* updated the default parameter value of `cyclocomp_linter` in the documentation from 25 to 15. Now it matches the default value in the function definition.
Closes #853

docs(cyclocomp_linter.R): updated the default parameter value

---

R/missing_argument_linter.R
tests/testthat/test-missing_argument_linter.R

Closes #906 
This PR makes `missing_argument_linter` ignores `COMMENT` nodes.

missing_argument_linter ignores comments

---

tests/testthat/test-object_usage_linter.R

Alternatively we could (1) pick a more obscure function name like `__lintr_missing_fun` (2) loop over the letters and pick the first one that fails `exists()`

add a skip for when the test might fail

---

R/object_name_linters.R
R/path_linters.R
tests/testthat/test-linter_tags.R

Part of #916
This has been the biggest pain point thus far -- making sure to remember the .csv is in sync as we make edits/rename things. Having this test will at least make it so we fail early.
Renamed the only two `_linter` objects in our namespace that aren't linters; thankfully neither is exported so we don't have to worry much.

add a test to ensure inst/lintr/linters.csv is up to date

---

R/T_and_F_symbol_linter.R
R/equals_na_linter.R
R/expect_not_linter.R
R/expect_s3_class_linter.R
R/paren_body_linter.R
R/pipe_call_linter.R
R/spaces_left_parentheses_linter.R
R/xp_utils.R

Part 1 split off from #956 
This way we don't keep accumulating little helper functions to pull out a lint message to pass on to `xml_nodes_to_lint()`
Rename the argument `message=` ➡️ `lint_message=` to avoid writing `message <- message(expr)` which looks like `base::message()`

extend xml_nodes_to_lint for custom messages

---

.dev/compare_branches.R
.gitignore

Also did a few ergonomic improvements:
- Don't litter console output with package startup messages. They make `--help` very hard to read.
- Removed the historical default linter (object_usage_linter) because it makes to sense.
- Added `--base-branch=master` option to modify the reference branch.
- Stopped littering `~` with result files, instead write to the `.dev` directory in lintr and `.gitignore` the generated csv files.
This makes working with the results from an IDE much easier.
Could still use a safeguard against Ctrl+C leaving interactive sessions in the `tempdir()` with the need to manually `unlink()` because subsequent runs of the script in the same session fail due to `Rtmp.../lintr_repo` being non-empty.

extend compare_branches to compare two branches

---

NEWS.md
R/comments.R
tests/testthat/test-comments.R

The GitHub repo slug can be determined from `GIT_URL`.
If there are multiple repo's, you can expect GitHub to be in `GIT_URL_1`.
For PRs, the pull request ID is in `CHANGE_ID`.
For other builds, the latest commit is in `GIT_COMMIT`.
Fixes #488

Detect Jenkins CI

---

NEWS.md
R/get_source_expressions.R
tests/testthat/test-get_source_expressions.R

Split off from #1032 because in principle it could affect the logic whenever `STR_CONST` is involved (especially, it's probably needed as part of #1034)

fix-up R parser bug in get_source_expressions

---

NEWS.md
R/yoda_test_linter.R
tests/testthat/test-yoda_test_linter.R

Closes #1067 
Based against #1065 for now.

yoda test linter doesnt lint on expect_equal(x$"key", 2)

---

NEWS.md
R/brace_linter.R
R/paren_brace_linter.R
R/zzz.R
inst/lintr/linters.csv
man/brace_linter.Rd
man/default_linters.Rd
man/linters.Rd
man/paren_brace_linter.Rd
tests/testthat/test-brace_linter.R
tests/testthat/test-paren_brace_linter.R

Based against #1096, part of #1041
* added lints for `else{` and `repeat{` while I was at it.

merge paren_brace_linter into brace_linter

---

NEWS.md
R/brace_linter.R
R/open_curly_linter.R
R/paren_brace_linter.R
R/zzz.R
inst/lintr/linters.csv
man/brace_linter.Rd
man/default_linters.Rd
man/linters.Rd
man/open_curly_linter.Rd
man/paren_brace_linter.Rd
tests/testthat/test-brace_linter.R
tests/testthat/test-open_curly_linter.R
tests/testthat/test-paren_brace_linter.R

Based against #1095, part of #1041
- remove open_curly_linter from defaults
- refactor to XPath based approach
- no longer lint trailing whitespace (there's a separate linter for that)

deprecate open_curly_linter and merge it into brace_linter

---

.lintr
.lintr_new
R/condition_message_linter.R
R/get_source_expressions.R
R/missing_package_linter.R
R/object_usage_linter.R
R/paste_linter.R
R/semicolon_linter.R
R/single_quotes_linter.R
tests/testthat/test-object_usage_linter.R

remove all easy to clean lints from master.
Notable exception: `lint()` has reached a cyclocomp of 37, mainly due to compatibility layer and the outstanding PR to factor out the cache complexity.
I also added `implicit_integer_linter()` to `.lintr_new` in line with #699.
However, master currently has 449 implicit integer lints, so not enabling it yet.

de-lint master

---

README.md

The publisher id of the vscode-R extension has been updated:
https://marketplace.visualstudio.com/items?itemName=REditorSupport.r
The installation command should reflect this change accordingly.
See https://github.com/REditorSupport/vscode-R/issues/690#issuecomment-1115829408.

Update VS Code R extension id

---

R/cache.R
R/get_source_expressions.R
R/lint.R
tests/testthat/test-comments.R
tests/testthat/test-error.R
tests/testthat/test-yoda_test_linter.R

Fixes #1128, based against #1129 to prevent r-devel build failures.
The changes are:
- suppress warnings during `load()`, since these aren't really helpful anyway if cache loading fails and hard to track down if it doesn't
- fix false positive argument deprecation warnings by also checking the positional argument is unnamed
- fix testthat 3e warnings for `setup()` and `teardown()` by using `local_envvar()`. I've locally confirmed that setting an envvar to `NA_character_` has the same effect as `Sys.unsetenv()`.
- Unified R version based skips (test-yoda_test_linter still tested for package base version instead of using `skip_if_not_r_version()`)
Browsing the logs, we can see that R <= 3.6.3 produces ~ 100 Warnings due to a bug in `utils::isS3StdGeneric()` which I don't think is worth …

Fix test warnings

---

NEWS.md
R/trailing_whitespace_linter.R
man/trailing_whitespace_linter.Rd
tests/testthat/test-trailing_whitespace_linter.R

Fixes #1045
Works by excluding all lines which are within a STR_CONST (`@line1` to `@line2 - 1`).
The last line doesn't need to be excluded because STR_CONST is guaranteed to end in a non-blank, so trailing whitespace after it should lint.

Ignore trailing whitespace in strings by default

---

.github/workflows/lint-changed-files.yaml
DESCRIPTION
README.md
vignettes/creating_linters.Rmd

This replaces `jimhester` with `r-lib` in the GitHub URLs / repo address.
Questions:
1. The URL in the `lint-changed-file.yaml` needs to be changed as well, I assume?
https://github.com/r-lib/lintr/blob/4ca7e484bcbe538cc5a81338c0ec55a0ae084cb0/.github/workflows/lint-changed-files.yaml#L35
2. Is the [gitter chat](https://github.com/dpprdan/lintr/blob/9fa72489b5d641312ca7c27128599298a7f0b506/README.md?plain=1#L5) still maintained? The last activity was over a year ago, AFAICT.

change lintr URLs to r-lib org

---

NEWS.md
R/brace_linter.R
tests/testthat/test-brace_linter.R

quick fix to #487 (also allow `(\n{`)

allow (\n{ in brace_linter

---

NEWS.md
R/object_usage_linter.R
tests/testthat/test-object_usage_linter.R

Partially fixes #1127.
The example provided in the original issue is more complex because `library(tidyverse)` doesn't export the functions used.
Instead, it attaches other packages as a side-effect. I don't have a good idea how to (without acutally running `library(...)`) detect these.
IIRC, the packages aren't even registered as `Depends`.

Auto-detect imported objects from packages in `object_usage_linter()`

---

NEWS.md
R/T_and_F_symbol_linter.R
R/exclude.R
R/function_left_parentheses.R
R/lint.R
R/methods.R
R/utils.R
man/exclude.Rd
man/parse_exclusions.Rd
tests/testthat/dummy_projects/project/partially_matched_exclusions.R
tests/testthat/test-exclusions.R
vignettes/using_lintr.Rmd

fixes #872 
- transitioned our internal `# nolint`s to the short-hand notation
- we raise a warning if no linter could be matched by an exclusion
- documented the short-hand notation
- added an example in the `using_lintr` vignette
- added tests
- extended NEWS bullet for #660

Use partial matching for linter names in exclusion directives

---

R/class_equals_linter.R
R/condition_message_linter.R
R/conjunct_test_linter.R
R/duplicate_argument_linter.R
R/expect_comparison_linter.R
R/expect_length_linter.R
R/expect_named_linter.R
R/expect_null_linter.R
R/expect_s3_class_linter.R
R/expect_true_false_linter.R
R/expect_type_linter.R
R/ifelse_censor_linter.R
R/inner_combine_linter.R
R/nested_ifelse_linter.R
R/outer_negation_linter.R
R/paste_linter.R
R/redundant_ifelse_linter.R
R/system_file_linter.R
R/unused_import_linter.R
R/utils.R
R/xp_utils.R
R/yoda_test_linter.R

Closes #1151 
Also introduce a new helper for the very common use case of `xml_find_char(expr, "string(SYMBOL_FUNCTION_CALL)")` (possibly nested at `expr/` or `expr/expr/` etc)
FWIW a quick test suggests it's about 20% faster to use `xml_find_char()` as well.

Use xml_find_chr where appropriate

---

NEWS.md
R/zzz.R
man/default_undesirable_functions.Rd

Sister to #1133 for `all_undesirable_operators`.

explain undesirable operators in Rd and lint message

---

R/assignment_linter.R
R/backport_linter.R
R/infix_spaces_linter.R
R/object_usage_linter.R
R/package_hooks_linter.R
R/undesirable_function_linter.R
R/vector_logic_linter.R

Rewrote all `//*[(self::xxx or self::yyy) and zzz]` constructs to the faster `//xxx[zzz] | //xxx[zzz]` XPath representation.

improve performance of XPath linters using //* predicates

---

R/get_source_expressions.R

Another 20% performance improvement by parsing the XML only once and creating the expression documents from the full document.
```
> system.time(get_source_expressions(test_file))
user  system elapsed 
2.099   0.001   2.099 
> devtools::load_all()
ℹ Loading lintr
> system.time(get_source_expressions(test_file))
user  system elapsed 
1.635   0.001   1.636 
```

generate expression xml parse data from full xml parse data

---

R/utils.R
R/with.R
tests/testthat/test-settings.R

Partially fixes #1193
```
lintr::lint(text = "a = 1 # nolint: implicit_integer.", linters = lintr::implicit_integer_linter())
```
is silent with this fix because `lintr::implicit_integer_linter()` is correctly named `"implicit_integer_linter"`.

remove package prefix from auto-generated names

---

R/commas_linter.R

refactor commas_linter to XPath

---

R/open_curly_linter.R
lintr.Rproj
tests/testthat/test-open_curly_linter.R

simplify open_curly_linter using xpath

---

R/exclude.R

Part of #1186
- use names2() instead of branching conditional on is.null(names(...)) and treating names() == "" separately
- move full_line_exclusions out of the any(unnamed) branch

reduce cyclocomp of normalize_exclusions() to 15

---

R/closed_curly_linter.R
man/closed_curly_linter.Rd

Part of #1186 
I just copied the refactored XPath logic from `brace_linter()`.

refactor closed_curly_linter() to XPath (reduces cyclocomp to 4)

---

NEWS.md

PS after this I'll just start pushing directly to #834 unless I think it warrants extra scrutiny -- check individual commit diffs there

use bullets in brace_linter deprecation note

---

R/any_is_na_linter.R
R/assignment_linter.R

Part of #1199 
Again pausing to send a separate PR since `assignment_linter()` is not quite trivial -- we've vectorized the lint message here, too.
`any_is_na_linter()` included because that one is trivial and I'm going in order

move logic to factory in any_is_na_linter and assignment_linter

---

R/any_duplicated_linter.R
tests/testthat/test-any_duplicated_linter.R

Part of #1199 
Filed separately because it's not a trivial refactor -- in addition to pulling the xpaths into the factory, I (1) deleted duplicate leftover code; (2) customized the lint to whether it's a lint on `length(unique(x$col)) == nrow(x)` or `length(unique(x)) == length(x)`; and (3) vectorized the `xml_nodes_to_lints()` call

pull any_duplicated xpaths into factory, and customize message

---

R/backport_linter.R
tests/testthat/test-backport_linter.R

Part of #1199 
Refactored a bit in order to vectorize the `lint_message` more cleanly -- see comment. Also switched to `xml_nodes_to_lints()`

backports_linter logic into factory, vectorize message

---

R/package_hooks_linter.R

Part of #1199 
Here's a case where deprecating `is.function(lint_message)` will take a bit more effort -- currently the function is nested a few layers deep, vectorizing is not quite as trivial.

pull out static objects to factory for package_hooks_linter

---

R/is_lint_level.R
R/spaces_left_parentheses_linter.R
R/utils.R
tests/testthat/test-error.R
tests/testthat/test-get_source_expressions.R

Closes #1262
- I think `key %in% names()` is a better test than `is.null()`
- But that's not enough -- both of these tests fail without also returning `xml2::xml_null()` from `safe_parse_to_xml()`:
https://github.com/r-lib/lintr/blob/53fd047406ea8e498e5f252578d6bc1741fa861a/tests/testthat/test-error.R#L3
https://github.com/r-lib/lintr/blob/53fd047406ea8e498e5f252578d6bc1741fa861a/tests/testthat/test-duplicate_argument_linter.R#L79

Handle NULL full_parsed_content --> missing full_xml_parsed_content

---

R/extraction_operator_linter.R

fixes #1260 
Why do we lint `NULL_CONST` at all?
```r
letters[NULL]
#> character(0)
letters[[NULL]]
#> Error in letters[[NULL]]: attempt to select less than one element in get1index
```
LMK if I should remove `NULL_CONST` from the list of allowed children.

extraction_operator_linter to XPath

---

R/extraction_operator_linter.R
tests/testthat/test-extraction_operator_linter.R

fixes #1273
needs a news bullet in #834 once merged

don't lint `a[NULL]` in `extraction_operator_linter()`

---

R/exclude.R
tests/testthat/test-unneeded_concatenation_linter.R

fixes #1219  and a small lint introduced by refactoring unneeded_concatenation_linter().

use @eval magic to avoid # nolint warning

---

R/unneeded_concatenation_linter.R
tests/testthat/test-unneeded_concatenation_linter.R

Closes #1301 
Also switched the XPath to be relative to the `parent::expr` of the current XPath. That's more consistent with some other XPaths and also makes things easier to write as we don't need as many `preceding-sibling::`/`following-sibling::`/`parent::` paths

unneeded_concatentation_linter skips named constants

---

tests/testthat/test-spaces_left_parentheses_linter.R

Just found a local patch that added edited `spaces_left_parentheses_linter()` and added some tests. Current dev version already passes the tests, so no need for the edit, but can't hurt to add a few regression tests.

upstream extra spaces_left_parentheses_linter tests

---

R/unneeded_concatenation_linter.R
tests/testthat/test-unneeded_concatenation_linter.R

use EQ_SUB instead of SYMBOL_SUB to detect named c() calls

---

R/object_usage_linter.R
tests/testthat/test-object_usage_linter.R

fix object_usage_linter() XPath for `assign()` and `setMethod()`

---

vignettes/editors.Rmd

The vscode-R publisher id is changed: https://github.com/REditorSupport/vscode-R/issues/690.

Update vscode-R link

---

R/spaces_inside_linter.R
tests/testthat/test-spaces_inside_linter.R

Closes #1343 
Issue was because we landed on the previous `<expr>` and used its `@line1`, which is wrong.

anchor to right paren to ensure better lint markers in spaces_inside_linter

---

R/infix_spaces_linter.R
tests/testthat/test-infix_spaces_linter.R

Closes #1342
The issue with
```
x +
y+
z
```
is that operator precedence means the tree looks like `(x + y)+ z`, and the `expr/@line1` != `+/@line1`, so the linter thought they were on different lines. Corrected to use `expr/@line2` instead, and switched to `@start`/`@end` which should be more reliable anyway.

anchor to start/stop, not columns, for multi-line expr

---

NEWS.md
R/with.R
tests/testthat/test-with.R

Closes #1361 
Alternatively, we could just support `defaults = NULL` in `modify_defaults()` directly.

with_defaults(default=NULL continues to work

---

NEWS.md
R/actions.R
R/lint.R
R/methods.R
tests/testthat/test-rstudio_markers.R

fixes #1357 
Didn't touch `checkstyle_output()`.
CC @renkun-ken Not sure if this is relevant to the vscode linter support.

prefix [linter_name] to all human-readable output formats

---

R/namespace.R
R/object_name_linters.R
man/object_length_linter.Rd
man/object_name_linter.Rd
tests/testthat/dummy_packages/missing_dep/DESCRIPTION
tests/testthat/dummy_packages/missing_dep/NAMESPACE
tests/testthat/dummy_packages/missing_dep/R/foo.R
tests/testthat/test-object_length_linter.R
tests/testthat/test-object_name_linter.R
tests/testthat/test-object_usage_linter.R

Closes #1360
The tests are not very satisfying -- they basically just guarantee running `lint()` doesn't fail in this case.
Considered making a little "cache" to throw a warning, but opted for a long explanation in the documentation instead. I think that's a good compromise. See #1366 for a way forward on this.

Skip unloadable namespaces when populating imports

---

.dev/compare_branches.R

Quick fix that can be landed right away

Rename old master branch to main in .dev/compare_branches

---

NEWS.md
R/missing_argument_linter.R
man/missing_argument_linter.Rd
tests/testthat/test-missing_argument_linter.R

fixes #1152 
deferring the NEWS bullet until #1384 is merged to avoid conflicts.

add `allow_trailing = FALSE` to `missing_argument_linter()`

---

R/lint.R
man/lint.Rd

to preserve old doc links to `lintr::lint()`

alias `?lint_file` -> `?lint`

---

tests/testthat/test-object_usage_linter.R

Test fails if `library(xml2)` is run before the suite starts, so just skip if it's attached to this session.

skip test if xml2 attached

---

NEWS.md
R/seq_linter.R
man/seq_linter.Rd
tests/testthat/test-seq_linter.R

`seq_linter` lints on dplyr and data.table flavors

---

NEWS.md
R/extract.R
R/trailing_blank_lines_linter.R
tests/testthat/test-trailing_blank_lines_linter.R

Don't omit trailing non-code lines from knitr files

---

NEWS.md
vignettes/lintr.Rmd

Exclude is the regex for `# nolint`, exclusions is for specifying exclusions.
fixes #1401

fix documentation reference to exclusions

---

DESCRIPTION
NEWS.md
tests/testthat/test-ci.R
tests/testthat/test-get_source_expressions.R
tests/testthat/test-parse_exclusions.R
tests/testthat/test-rstudio_markers.R
tests/testthat/test-trailing_blank_lines_linter.R
tests/testthat/test-xml_nodes_to_lints.R

In order to use the `lines` parameter from `withr::local_tempfile()`.
Closes #1404

Bump needed `{withr}` version

---

NEWS.md
R/lint.R
R/utils.R
R/with.R
tests/testthat/test-linter_tags.R
tests/testthat/test-with.R

Closes #1392 
I don't see any references to the `lintr_function` class anywhere, but elsewhere we test `inherits(x, "linter")`. So I assume that's an oversight and we only want one `"linter"` class.

use consistent linter class, add membership helper

---

DESCRIPTION
tests/testthat/test-paren_body_linter.R

Alternatively, we could just bump the version requirement to 1.0.5

add version requirement for OP-LAMBDA

---

NEWS.md
R/redundant_ifelse_linter.R
tests/testthat/test-redundant_ifelse_linter.R

Update message for redundant ifelse linter

---

tests/testthat/test-with.R

Since 'covr' is just Suggests & this is the only place in tests requiring it

don't try covr:: if covr unavailable

---

NEWS.md
R/exclude.R
tests/testthat/test-exclusions.R

Fix `is_excluded_file()` again

---

R/vector_logic_linter.R
man/vector_logic_linter.Rd

Related to #1453. We won't be able to detect such cases statically -- users will just have to disable / turn off the linter if their code heavily relies on some `&` or `|` method inside `if()` statements.

Add a note about &/| dispatch

---

NEWS.md
R/get_source_expressions.R
R/lint.R
R/tree-utils.R
tests/testthat/test-get_source_expressions.R

Closes #1443
Not totally happy we've solved the problem with a high level of generality, but it does close the issue at hand.

skip evaluation that hangs on bad input

---

DESCRIPTION
NEWS.md
R/seq_linter.R
man/ids_with_token.Rd
man/lint.Rd
man/seq_linter.Rd
man/vector_logic_linter.Rd
tests/testthat/test-seq_linter.R

Closes #1467
TODO
``` r
library(lintr)
lint(
text = "seq(length(mtcars))",
linters = seq_linter()
)
#> <text>:1:1: warning: [seq_linter] seq(length(...)) is likely to be wrong in the empty edge case. Use seq_along(...) instead.
#> seq(length(mtcars))
#> ^~~~~~~~~~~~~~~~~~~
lint(
text = "seq(nrow(mtcars))",
linters = seq_linter()
)
#> <text>:1:1: warning: [seq_linter] seq(nrow(...)) is likely to be wrong in the empty edge case. Use seq_len(...) instead.
#> seq(nrow(mtcars))
#> ^~~~~~~~~~~~~~~~~
```
<sup>Created on 2022-07-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Remove false negative in `seq_linter()`

---

NEWS.md
R/namespace.R
tests/testthat/dummy_packages/no_export_dep/DESCRIPTION
tests/testthat/dummy_packages/no_export_dep/NAMESPACE
tests/testthat/dummy_packages/no_export_dep/R/foo.R
tests/testthat/test-object_length_linter.R

Handle dependencies with no exports

---

.github/workflows/lint-changed-files.yaml
tests/testthat/test-closed_curly_linter.R

Closes #1489
This seems to be working: https://github.com/r-lib/lintr/runs/8070424277?check_suite_focus=true

GHA workflow `lint-changed-files` fails when a new lint is found in changed files

---

_pkgdown.yml

This is the reason why the package version in navigation bar looks so dull:
It's either this, or we add the following to `pkgdown/extra.scss`:
```css
.nav-text.text-default.me-auto {
color: rgba(0,0,0,0.9) !important;
}
```
I prefer the first solution, which I have implemented in this PR. No strong opinions, though. Happy to also add the aforementioned CSS.

Get rid of version label and tooltip

---

NEWS.md

I don't see any meaningful distinction b/w "New features" and "New and improved features"

Collapse near-identical sections in NEWS of 3.0.1

---

NEWS.md
R/fixed_regex_linter.R
tests/testthat/test-fixed_regex_linter.R

Closes #1545
``` r
lintr::lint(
'strsplit("a;b", split = "\\\\;")\n', 
lintr::fixed_regex_linter()
)
#> <text>:1:25: warning: [fixed_regex_linter] This regular expression is static, i.e., its matches can be expressed as a fixed substring expression, which is faster to compute. Here, you can use ";" with fixed = TRUE.
#> strsplit("a;b", split = "\\;")
#>                         ^~~~~
```
<sup>Created on 2022-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

`fixed_regex_linter()` doesn't fail with `"\\;"`

---

R/unused_import_linter.R
tests/testthat/test-unused_import_linter.R

Follow-up to #1549, the `Items` column has a funny format for some objects, per `?data`:
```
Where the datasets have a different name from the
argument that should be used to retrieve them the index will have
an entry like ‘beaver1 (beavers)’ which tells us that dataset
‘beaver1’ can be retrieved by the call ‘data(beaver)’.
```
From experimenting, it looks like `beaver1` is the one we want to allow.

Slightly improve dataset symbol detection

---

.lintr_new

As discussed here: https://github.com/r-lib/lintr/pull/1548#discussion_r979355818

Include `expect_*()` linters in `.lintr_new`

---

R/expect_lint.R
man/expect_lint.Rd

We're currently getting a NOTE because of width>100 characters in examples

Examples for ?expect_lint too wide for R CMD check

---

R/extraction_operator_linter.R
R/redundant_equals_linter.R
man/extraction_operator_linter.Rd

Update docs for `extraction_operator_linter()`

---

R/class_equals_linter.R
R/expect_identical_linter.R
R/expect_named_linter.R
R/expect_not_linter.R
R/expect_null_linter.R
R/expect_true_false_linter.R
R/redundant_ifelse_linter.R
R/regex_subset_linter.R
R/unused_import_linter.R

Closes #1358 
Two more linters (`expect_named_linter()`, `expect_null_linter()`) anchor to the "normal" `<expr>` node, hence the removal of `depth=0`; no tests needed to be updated, but the associated metadata will have changed.

Complete switch away from //expr XPaths

---

R/linter_tags.R

cf. https://github.com/r-lib/lintr/pull/1626#issuecomment-1270184481

Add nocov directives to Rd fragment functions

---

.lintr_new
NEWS.md
R/extract.R
tests/testthat/test-get_source_expressions.R

Closes #779
I didn't see any `<<examples>>` included with {knitr}, but the solution is simple enough & basically re-uses stuff directly from {knitr}, so I didn't feel too compelled to add any more tests.

Handle <<reference_chunks>> in Rnw,Rmd

---

NEWS.md
R/lint.R
man/lint-s3.Rd
man/lint.Rd
tests/testthat/test-lint_file.R
tests/testthat/test-methods.R

Add "list" to S3 class of lint(), Lint() output

---

NEWS.md
R/spaces_inside_linter.R
tests/testthat/test-infix_spaces_linter.R
tests/testthat/test-spaces_inside_linter.R

handle alist(kwd = ) false positive

---

tests/testthat.R
tests/testthat/helper.R
tests/testthat/test-backport_linter.R
tests/testthat/test-cache.R
tests/testthat/test-checkstyle_output.R
tests/testthat/test-get_source_expressions.R
tests/testthat/test-lint_file.R
tests/testthat/test-lint_package.R
tests/testthat/test-methods.R
tests/testthat/test-normalize_exclusions.R
tests/testthat/test-parse_exclusions.R
tests/testthat/test-settings.R

I couldn't remove all `on.exit()` usages, here's what remains:
```r
tests/testthat/test-error.R:29:  on.exit(lintr:::reset_lang(old_lang), add = TRUE)
tests/testthat/test-get_source_expressions.R:5:    on.exit(close(con))
tests/testthat/test-object_usage_linter.R:312:  on.exit(utils::globalVariables(old_globals, package = globalenv(), add = FALSE))
tests/testthat/test-settings.R:61:  on.exit(if (is.na(old)) Sys.unsetenv(test_env) else sym_set_env(test_env, old))
```
Of those
- test-error.R: can't be removed unless we add a custom unexported `local_lang()`
- test-get_source_expressions.R: see https://github.com/r-lib/withr/issues/210
- test-object_usage_linter.R: I support we could use `withr::defer()`, but `on.exit()` seems fine here
- test-settings.R: this _may_ be replaced by …

Use {withr} more comprehensively in tests to manage state

---

tests/testthat/test-namespace_linter.R

I also wanted to add a test for Case-2 here, which currently isn't tested. But I couldn't come up with one. 
Is it even possible for a package to be installed with a broken `NAMESPACE`?
https://github.com/r-lib/lintr/blob/0af31f53a1007e464cf975bf9d62e79b484a7f35/R/namespace_linter.R#L54-L71

Additional test for `namespace_linter()`+ clean-up

---

tests/testthat/test-absolute_path_linter.R
tests/testthat/test-assignment_linter.R
tests/testthat/test-brace_linter.R
tests/testthat/test-class_equals_linter.R
tests/testthat/test-commented_code_linter.R
tests/testthat/test-cyclocomp_linter.R
tests/testthat/test-duplicate_argument_linter.R
tests/testthat/test-equals_na_linter.R
tests/testthat/test-expect_identical_linter.R
tests/testthat/test-expect_lint.R
tests/testthat/test-get_source_expressions.R
tests/testthat/test-line_length_linter.R
tests/testthat/test-missing_argument_linter.R
tests/testthat/test-missing_package_linter.R
tests/testthat/test-no_tab_linter.R
tests/testthat/test-nonportable_path_linter.R
tests/testthat/test-object_name_linter.R
tests/testthat/test-paren_body_linter.R
tests/testthat/test-paren_brace_linter.R
tests/testthat/test-redundant_equals_linter.R
tests/testthat/test-single_quotes_linter.R
tests/testthat/test-spaces_left_parentheses_linter.R
tests/testthat/test-strings_as_factors_linter.R
tests/testthat/test-todo_comment_linter.R
tests/testthat/test-trailing_blank_lines_linter.R
tests/testthat/test-trailing_whitespace_linter.R
tests/testthat/test-unused_import_linter.R
tests/testthat/test-with.R
tests/testthat/test-xml_nodes_to_lints.R

Currently, in some tests we use `msg`, while in others `lint_msg`.

Consistently use `lint_msg` instead of `msg`

---

NEWS.md
R/spaces_inside_linter.R
tests/testthat/test-spaces_inside_linter.R

`spaces_inside_linter()` lints spaces after `[[`

---

R/unnecessary_placeholder_linter.R
man/sprintf_linter.Rd
man/unnecessary_placeholder_linter.Rd
tests/testthat/test-unnecessary_placeholder_linter.R

`unnecessary_placeholder_linter()` covers a few other ops

---

R/comment_linters.R
R/trailing_blank_lines_linter.R
R/trailing_whitespace_linter.R
R/undesirable_function_linter.R
R/undesirable_operator_linter.R
R/unneeded_concatenation_linter.R
R/unreachable_code_linter.R
R/unused_import_linter.R
R/vector_logic_linter.R
R/yoda_test_linter.R
man/todo_comment_linter.Rd
man/trailing_blank_lines_linter.Rd
man/trailing_whitespace_linter.Rd
man/undesirable_function_linter.Rd
man/undesirable_operator_linter.Rd
man/unneeded_concatenation_linter.Rd
man/unreachable_code_linter.Rd
man/unused_import_linter.Rd
man/vector_logic_linter.Rd
man/yoda_test_linter.Rd
tests/testthat/test-vector_logic_linter.R

Part of https://github.com/r-lib/lintr/issues/1492
Doesn't close the issue yet. A couple of items and some cleanup remaining.

Add examples to documentation: Part-8 (t-z)

---

R/no_tab_linter.R
man/no_tab_linter.Rd

Further reading for no tabs linter

---

tests/testthat/test-implicit_integer_linter.R

use parameterized test on public API for implicit_integer_linter()

---

NEWS.md
R/implicit_integer_linter.R
inst/lintr/linters.csv
man/configurable_linters.Rd
man/implicit_integer_linter.Rd
man/linters.Rd
tests/testthat/test-implicit_integer_linter.R

1:10 doesnt lint, optionally

---

R/expect_lint.R

I believe this is the source of a warning about unclosed connections I get occasionally.
My thinking is like this:
```
expect_lint(stop(), NULL, linter())
```
`stop()` won't evaluate until after the temporary connection is opened, then `close()` won't run.
We also can't add this `close()` to the overall `on.exit()` call since we need the connection to close in order to lint it.

always close con

---

R/unnecessary_lambda_linter.R
tests/testthat/test-unnecessary_lambda_linter.R

unnecessary_lambda_linter catches functions with braces

---

tests/testthat/test-for_loop_index_linter.R
tests/testthat/test-missing_package_linter.R
tests/testthat/test-settings.R
tests/testthat/test-undesirable_operator_linter.R

- formatting
- use `:::` for internals
- skip vs block division of tests

Minor cleanup in tests

---

.dev/revdep_get_repos.R
.lintr_new
tests/testthat/test-linter_tags.R

Also add the corresponding linter to our workflow

Include `stringsAsFactors = FALSE` where relevant

---

tests/testthat/test-linter_tags.R
tests/testthat/test-use_lintr.R
tests/testthat/test-with_id.R

Missed a few in https://github.com/r-lib/lintr/pull/1712

Get rid of `expect_identical_linter()` lints: Part-2

---

tests/testthat/test-commented_code_linter.R

Part of #1692
And cleanup to break the tests down into skip vs block blocks.

Use public interface to test internal functions: Part-3

---

tests/testthat.R

cf. https://github.com/r-lib/lintr/pull/1739#discussion_r999745186

Remove unnecessary `loadNamespace()` call for `{rex}`

---

R/ids_with_token.R
man/ids_with_token.Rd

Triggers `function_argument_linter()`:
> Arguments without defaults should come before arguments with defaults.

Add nolint for `ids_with_token()` definition

---

.lintr_new
R/expect_lint.R
R/get_source_expressions.R
R/lint.R
R/object_usage_linter.R
R/utils.R
R/zzz.R
tests/testthat/test-settings.R

Closes #1766
Add it back once #1692 is resolved

Remove `undesirable_operator_linter()` from `.lintr_new`

---

R/indentation_linter.R
man/indentation_linter.Rd
tests/testthat/test-indentation_linter.R

The issue in the reprex was `xp_block_ends` landed on line 1 because the comment was sitting there. It should have ended on line 2.

Enhance and fix `indentation_linter`

---

.github/workflows/check-all-examples.yaml
DESCRIPTION
R/lint.R
R/use_lintr.R
R/with.R
man/lint.Rd
man/linters_with_tags.Rd
man/use_lintr.Rd

Closes #1775 
`\donttest` examples are run in [an additional check](https://www.stats.ox.ac.uk/pub/bdr/donttest/) by BDR, and probably `\dontrun` examples are also run in some other checks. 
Therefore, making sure all examples run successfully (or are never run if they are just for illustrative purposes) is a good preventive practice, in general. This is currently not true for lintr-main branch, and is remedied in this PR.

Fix examples and add a new workflow to catch any future failures

---

R/with.R
man/linters_with_tags.Rd

Including definitions of functions makes the output on the website quite overwhelming.
cf. https://lintr.r-lib.org/dev/reference/linters_with_tags.html#ref-examples

Include only names of linters in example outputs

---

NEWS.md
R/with.R
tests/testthat/test-lint_file.R

fixes #1725 
``` r
waldo::compare(lintr::linters_with_defaults(assignment_linter = lintr::assignment_linter)["assignment_linter"], list(assignment_linter = lintr::assignment_linter))
#> `old$assignment_linter` is an S3 object of class <linter/function>, a function
#> `new$assignment_linter` is a function
```
<sup>Created on 2022-12-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
``` r
waldo::compare(lintr::linters_with_defaults(assignment_linter = lintr::assignment_linter)["assignment_linter"], list(assignment_linter = lintr::assignment_linter))
#> ✔ No differences
lintr::lint(text = "a = 1", linters = lintr::linters_with_defaults(assignment_linter = lintr::assignment_linter))
#> Warning: Passing linters as variables was deprecated in lintr version 3.0.0. Use
#> a call to the …
```

Don't mark linter factory functions as linters in `modify_defaults()`

---

README.md

Since `{remotes}` is the lightweight option.
``` r
length(tools::package_dependencies("devtools", recursive = TRUE)[[1L]])
#> [1] 100
length(tools::package_dependencies("remotes", recursive = TRUE)[[1L]])
#> [1] 4
```
<sup>Created on 2022-12-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

devtools -> remotes in installation instructions

---

NEWS.md
R/linter_tags.R
tests/testthat/test-linter_tags.R

Closes #1781
``` r
library(lintr)
rownames(available_linters())
#>  [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
#> [16] "16" "17" "18" "19" "20" "21" "22" "23" "24" "25" "26" "27" "28" "29" "30"
#> [31] "31" "32" "33" "34" "35" "36" "37" "38" "39" "40" "41" "42" "43" "44" "45"
#> [46] "46" "47" "48" "49" "50" "51" "52" "53" "54" "55" "56" "57" "58" "59" "60"
#> [61] "61" "62" "63" "64" "65" "66" "67" "68" "69" "70" "71" "72" "73" "74" "75"
#> [76] "76" "77" "78" "79" "80" "81" "82" "83" "84" "85" "86"
```
<sup>Created on 2022-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Fix missing row names in `available_linters()`

---

R/implicit_assignment_linter.R
tests/testthat/test-implicit_assignment_linter.R

Anticipate "no exceptions" case for `implicit_assignment_linter()`

---

tests/testthat/test-implicit_assignment_linter.R

Add tests for multi-line anonymous functions for `implicit_assignment_linter()`

---

R/brace_linter.R

Definitely a subjective choice, but I wonder if you feel the same way as I do; i.e., the formatting in this PR is better and more readable.

Improve formatting for `brace_linter()` file

---

R/lint.R
tests/testthat/test-sarif_output.R

* Ensure all `sarif_output()` generated files include `results` array even if linting results in no issues
* `results` is required to be present in a SARIF file to be successfully uploaded to GitHub
fixes #1836

Fix `sarif_output()` format when no linting produces no results

---

.github/workflows/R-CMD-check.yaml

For bookdown package update on CRAN. It now requires `R > 3.5`.
Closes #1853

Fix R CMD check workflow

---

tests/testthat/test-unneeded_concatenation_linter.R

Follow the skip vs block pattern in tests layout

Reorganize tests for `unneeded_concatenation_linter()`

---

R/addins.R

The entire file has been nocov-ed, so these two annotations are redundant.

Remove redundant nocov annotations in addins file

---

R/duplicate_argument_linter.R
R/extract.R
R/indentation_linter.R
R/methods.R

cf. https://style.tidyverse.org/syntax.html#implicit-type-coercion

Avoid implicit type coercion in conditional expressions using `length()`

---

NEWS.md
R/undesirable_function_linter.R
R/undesirable_operator_linter.R
tests/testthat/test-undesirable_function_linter.R
tests/testthat/test-undesirable_operator_linter.R

Error on empty character vector args in undesirable linters

---

R/implicit_assignment_linter.R
tests/testthat/test-implicit_assignment_linter.R

`implicit_assignment_linter()` doesn't produce false positives with walrus operator

---

tests/testthat/test-implicit_assignment_linter.R

For `implicit_assignment_linter()`

Separate out tests for allowed assignments with braces

---

R/condition_message_linter.R
man/condition_message_linter.Rd

Fix `condition_message_linter()` examples

---

NEWS.md
R/missing_argument_linter.R
man/missing_argument_linter.Rd
tests/testthat/test-missing_argument_linter.R

`missing_argument_linter()` allows missing arguments in `quote()` calls

---

vignettes/continuous-integration.Rmd

I gather from #1558 that lintr-bot is retired, so its mentions should be removed.
Re the Travis section in the vignette. {[HIBPwnd](https://github.com/jumpingrivers/HIBPwned/)} has been archived, so that is not a good example anymore. Do you have another one? Or should we just remove the whole Travis section since it is probably not used much anymore anyway?

remove mentions of lintr-bot

---

README.md

Inspired by https://github.com/r-lib/lintr/pull/1885#issuecomment-1382225238.
Maybe it would be good to clarify that the API is mature and stable upfront, without having to check version numbers in DESCRIPTION, assuming the reader is even familiar with SemVer.

Add lifecycle badge to README

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md

Supersedes https://github.com/r-lib/lintr/pull/1921.
The version bump is bigger than I thought, but we've only been testing on R3.4, so that feels to me like our implicit dependency is really R3.4 -- we don't know for sure that the package works on R3.2/R3.3 right? Which makes this a more gradual bump R3.4->R3.5.

Bump R dependency to R3.5

---

R/unnecessary_lambda_linter.R
man/unnecessary_lambda_linter.Rd
tests/testthat/test-unnecessary_lambda_linter.R

Haven't added examples for `map` family on account of #1871.

Add examples for `unnecessary_lambda_linter()`

---

R/extract.R

Closes #1920. Not an ideal solution but I'd rather just un-break our CI for now.

Let MBCS warning fall through the first time it's encountered

---

.github/workflows/R-CMD-check.yaml

We have a lot of .yml files where we could use this, I applied it to this one first since it's the costliest.
Is there an easy way to have a common config like this re-used across all of our jobs?

Quit in-progress CI runs on new commit

---

NEWS.md
R/with.R
tests/testthat/test-with.R

Example error message at the moment:
> Error in linters_with_tags(tags = NULL) :
Linters ‘implicit_assignment_linter’, ‘matrix_apply_linter’, ‘quotes_linter’and‘unnecessary_concatenation_linter’ advertised by `available_linters()` but not exported by package lintr.

Add missing spaces around "and" in glue_collapse()

---

NEWS.md
R/settings.R
R/settings_utils.R
R/zzz.R
man/read_settings.Rd
tests/testthat/test-settings.R
vignettes/lintr.Rmd

It would be great if the default lintr config would be preferentially looked up in the appropriate [XDG base configuration directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) instead of the user home directory. That is, if lintr defaulted to loading `${XDG_CONFIG_HOME-$HOME/.config}/lintr` (note lack of leading dot in the filename!) and only if that doesn’t exist, checked for `$HOME/.lintr`. This avoids cluttering the home directory with config files.
Of course this can already be achieved by appropriately setting the `lintr.linter_file` option. But defaults matter.
This PR implements the necessary change, and stays 100% backwards compatible. Note that this causes the cyclomatic complexity of the `find_config` function to exceed the linting threshold. …

Use XDG config directory

---

NEWS.md
R/object_usage_linter.R
R/quotes_linter.R
tests/testthat/test-object_usage_linter.R

Fix parsing usage warnings from codetools without location info

---

NEWS.md
R/methods.R
R/zzz.R
tests/testthat/test-methods.R

Closes #1997
As near as I can tell, this is the proper way to do an S3 registration for a `Suggests`/`Enhances` dependency.

Add an as_tibble method for class lints

---

DESCRIPTION
R/methods.R
R/zzz.R
tests/testthat/test-methods.R

Follow-up to #1998 -- actually `as.data.table()` experiences a similar regression from v3.0.2 to HEAD, just that it's not breaking any tested downstreams. I have relied on this behavior in interactive cases, though.
I _think_ the enigmatic `Enhances` is the proper place for the new dependency, [per WRE](https://cran.r-project.org/doc/manuals/R-exts.html#Package-Dependencies):
> ‘Enhances’... lists packages “enhanced” by the package at hand, e.g., by providing methods for classes from these packages...
OTOH we might just "keep it simple" and put data.table in `Suggests`.
---
Currently `as.data.table()` works very poorly b/c of dispatch:
```r
data.table::as.data.table(lintr::lint(text="a=1", linters=lintr::assignment_linter()))
```

also a method for as.data.table.lints

---

NEWS.md
R/object_name_linter.R
man/object_name_linter.Rd

Resolves https://github.com/r-lib/lintr/issues/1924 by adding a short description of the "symbols" style in the `object_name_linter` documentation.

document "symbols" in object_name_linter (#1924)

---

NEWS.md
R/inner_combine_linter.R
tests/testthat/test-inner_combine_linter.R

Closes #2017 
Confirming this is a regression introduced by 680715fc5411fcbefed55bff1dc7757d86ae061b:
```shell
git checkout 680715fc5411fcbefed55bff1dc7757d86ae061b~1
Rscript -e 'lintr::lint("\nc(exp())", lintr::inner_combine_linter())'
git checkout 680715fc5411fcbefed55bff1dc7757d86ae061b
Rscript -e 'lintr::lint("\nc(exp())", lintr::inner_combine_linter())'
```

skip c() unless >1 argument is used

---

NEWS.md
R/function_argument_linter.R
man/function_argument_linter.Rd

Seems there was a refactor in the last few days:
https://design.tidyverse.org/required-no-defaults.html
It looks like there's some clarification/exceptions added to the body, it might make sense to revisit when lints apply in light of that. But for now we just fix the links.

Update link to design guide

---

.lintr_new

rename deprecated lintrr

---

NEWS.md
R/assignment_linter.R
man/assignment_linter.Rd
tests/testthat/test-assignment_linter.R

lint %<>% in assignment_linter

---

R/infix_spaces_linter.R
tests/testthat/test-infix_spaces_linter.R

Similar to #2024, I found `infix_spaces_linter()` to be among the slowest, and apparently owing to the `//*` expression.
It's really slow! Even with 22 entries in `//NODE1[...] | //NODE2[...] | ... | //NODE22[...]`, I find this approach about 3x as fast in the core loop:
```r
exp <- get_source_expressions("QC.R")
ll <- lintr::infix_spaces_linter()
system.time(replicate(100, lapply(exp$expressions, ll)))
```

Use node-level | for efficiency in infix_spaces_linter

---

NEWS.md
R/object_usage_linter.R
tests/testthat/test-object_usage_linter.R

catch function calls in glue interpolation

---

R/function_argument_linter.R
R/indentation_linter.R
R/infix_spaces_linter.R
R/pipe_continuation_linter.R
R/redundant_equals_linter.R
R/vector_logic_linter.R

Re-examined in what situations `|` can be used.
Till now we've often conservatively used `//NODE1[ $BIG_EXPRESSION ] | //NODE2[ $BIG_EXPRESSION ]`, but this works fine: `(//NODE1 | //NODE2)[ $BIG_EXPRESSION ]`.
Untested as yet but I am assuming this can have some efficiency benefit (or at least not hurt, while hopefully making the code more readable).
Marking as draft for now since `infix_spaces_linter()` will likely benefit and #2025 is pending, but feel free to review the existing changes. I'll also try and add some timings.

Use | more judiciously

---

NEWS.md
R/condition_message_linter.R
tests/testthat/test-condition_message_linter.R

Skip extracted condition calls

---

NEWS.md
R/object_name_linter.R
tests/testthat/test-object_name_linter.R

Closes #1466
There's a few different ways we could fix this. I _think_ it would also be enough to look for nearby `SYMBOL_FUNCTION_CALL`.
I also think we can skip the `LBB` test for `STR_CONST`, but didn't bother looking too carefully for this PR.
NB: relevant test cases like `{a,"a"}${b,"b"} <- 1` are already present in the suite:
https://github.com/r-lib/lintr/blob/3e6b862da57817a488bc8b263d31ac17b4f99de6/tests/testthat/test-object_name_linter.R#L150-L155

Don't lint nested string literals on LHS of assignment

---

NEWS.md
R/library_call_linter.R
tests/testthat/test-library_call_linter.R

Closes #2045 
Maybe a renaming is in order? `attach_up_front_linter()`? `preamble_attach_linter()`? `package_preamble_linter()`?

require & library both linted in library_call_linter()

---

DESCRIPTION

Require backports >= 1.1.7

---

NEWS.md
R/conjunct_test_linter.R
man/conjunct_test_linter.Rd
tests/testthat/test-conjunct_test_linter.R

Fixes https://github.com/r-lib/lintr/issues/2108.

Allow to opt out of linting `filter()` in `conjunct_test_linter`

---

.github/dependabot.yaml

To avoid manually doing upkeep like in https://github.com/r-lib/lintr/pull/2119.
This Dependabot configuration is designed to keep GitHub Actions dependencies up-to-date
by running weekly checks and creating pull requests to update them as needed.
This ensures that the GitHub Actions workflows remain compatible with the latest versions
of their dependencies, potentially improving the stability and security of automation processes.
For more, see:
https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts

Add dependabot workflow

---

NEWS.md
R/library_call_linter.R
inst/lintr/linters.csv
man/configurable_linters.Rd
man/library_call_linter.Rd
man/linters.Rd
tests/testthat/test-library_call_linter.R

allow_preamble in library_call_linter() to skip setup code

---

NEWS.md
R/zzz.R

Adds `Sys.unsetenv()` to `default_undesirable_functions`

---

R/lint.R
tests/testthat/test-lint_dir.R

Accidentally linted a directory where everything was excluded, leading to an error from `txtProgressBar()`:
```
Error in txtProgressBar(max = length(files), style = 3L) : 
must have 'max' > 'min'
```
Better to just skip running anything if there's nothing to lint.

Return early if there's nothing to lint

---

R/settings_utils.R

Feeds into #2177
I found the structure of the `while()` loop confusing, it took me quite some time to figure out it's checking _both_ `${PATH}/.lintr` _and_ `${PATH}/.github/linters/.lintr` on each pass.
I hope this rewrite makes what's going on much clearer. It will also make it trivial to extend for #2177 to also check for `.lintr.R`.

Simplify find config

---

R/utils.R
R/xml_nodes_to_lints.R
R/xp_utils.R
tests/testthat/test-xp_utils.R

Well, not truly a refactoring because I am changing one error message.

Minor refactoring with XML node helpers

---

R/utils.R

`structure()` is IME always slower (admittedly on very small absolute scale) than the alternatives, with little tradeoff of readability (if anything I think using setters is more canonical -> more readable). E.g.
```r
library(microbenchmark)
l <- list()
f1 <- function(l) structure(l, class = c("a", "b"), name = "nm")
f2 <- function(l) {
class(l) <- c("a", "b")
attr(l, "name") <- "nm"
l
}
microbenchmark(times = 1e6, f1(l), f2(l))
identical(f1(l), f2(l))
```

avoid structure()

---

NEWS.md
R/unnecessary_lambda_linter.R
tests/testthat/test-unnecessary_lambda_linter.R

Fix false positives for extractions in lambdas

---

.github/workflows/R-CMD-check.yaml

I think we can get away with keeping R3.5.0 for this release since it's imminent, then bump our requirement to R>=3.6.0 immediately after release. Through today all of our tests have been passing on 3.5.0 so it's only CI that stopped for now.
Otherwise, we can make the next release 3.2.0 and bump our R dependency already.

Bump oldest test suite to R 3.6.0

---

R/unnecessary_lambda_linter.R
tests/testthat/test-unnecessary_lambda_linter.R

Closes #2249 
`//` starts from the top of the document, `.//` starts from within the current expression. Key difference in larger files!

Need relative, not global descendant in unnecessary_lambda_linter()

---

R/unused_import_linter.R

`requireNamespace("pkg")` does *load* pkg, but not *attach* it.

Be more precise

---

R/lint.R
R/settings.R
man/lint.Rd
man/read_settings.Rd

Link to [`read_settings()`](https://lintr.r-lib.org/reference/read_settings.html) where settings search order is defined. Plus some cosmetic changes.

Link to `read_settings()`

---

tests/testthat/test-unreachable_code_linter.R

Look at any recent run e.g. https://github.com/r-lib/lintr/actions/runs/6886554472

Fix test causing a warning in the lint GHA

---

R/comparison_negation_linter.R
R/nonportable_path_linter.R
R/sample_int_linter.R
R/scalar_in_linter.R
R/stopifnot_all_linter.R
R/terminal_close_linter.R
man/comparison_negation_linter.Rd
man/nonportable_path_linter.Rd
man/sample_int_linter.Rd
man/scalar_in_linter.Rd
man/stopifnot_all_linter.Rd
man/terminal_close_linter.Rd
tests/testthat/test-lintr-package.R

Thanks @IndrajeetPatil for catching the mistake of `sample_int_linter()` lacking examples. I added those, and looked for other doc pages lacking `@examples` -- a few more slipped through as well.
Therefore I added a regression test to guard against this going forward.

Ensure examples in linter docs

---

R/nonportable_path_linter.R
man/nonportable_path_linter.Rd

Uncaught error from #2288. Not being able to rely completely on GHA let this slip through.

Add () missing from nonportable_path_linter() example

---

NEWS.md
R/object_name_linter.R
tests/testthat/test-object_name_linter.R

Closes #2188
NB: We don't have any tests touching the `is.na(nms)` case. I guess that's because our XPath is good at ensuring we always find a variable name. Should we just drop that instead? Harmless I guess.

handle when re_matches returns a data.frame from capture groups

---

R/lint.R
tests/testthat/test-lint.R
tests/testthat/test-lint_dir.R

This became an error in 3.1.1, now we can remove it for the next release.

Remove error for deprecated functionality

---

NEWS.md
R/one_call_pipe_linter.R
man/one_call_pipe_linter.Rd
tests/testthat/test-one_call_pipe_linter.R

exclude %<>% from one_call_pipe_linter

---

R/object_overwrite_linter.R
tests/testthat/test-object_overwrite_linter.R

Related to #2337
This does not have much impact (there's only 3 overwrites in the default packages), but should be done anyway.

Drop duplicates from list of names in object_overwrite_linter()

---

R/backport_linter.R

Related: #2338. This is not the primary source of inefficiency but should nevertheless remove some overhead.

move test outside loop in backport_linter factory

---

R/object_overwrite_linter.R

```r
system.time(lint_package(linters = object_overwrite_linter()))
```
While working on it, I wondered, if the lint message could be made more elegant.
WDYT about
`"'fun' overwrites 'pkg::fun'. Avoid overwriting symbols from other packages."`

Speed up object_overwrite_linter

---

R/backport_linter.R
R/package_hooks_linter.R

Closes #2336
Also move to `"file"`-level linting, I think that makes more sense for this linter.
With this, `lint_package()` goes from taking 11s to 8s on my machine.
For reference, `make_linter_from_xpath("false", "xx")` also takes about 8s, i.e., most of that 11s is the overhead of loading the files.

exit early from package_hooks_linter() if no hooks are found

---

NEWS.md
R/methods.R
tests/testthat/test-methods.R

new width= parameter for output methods

---

R/vector_logic_linter.R
tests/testthat/test-vector_logic_linter.R

Mention the specific operator in lint message for vector_logic_linter()

---

R/implicit_integer_linter.R
tests/testthat/test-implicit_integer_linter.R

Closes #2388. Things are a bit hazier for lints like `1e3` where a more precise recommendation might be `1e3L or 1.0e3`. But it's easier to just remove the scientific notation: `1000L or 1000.0`.

Give specific example of explicit types in implicit_integer_linter() message

---

NEWS.md
R/expect_comparison_linter.R
tests/testthat/test-expect_comparison_linter.R

Only lint the first argument of expect_true() for expect_comparison_linter()

---

R/equals_na_linter.R
tests/testthat/test-equals_na_linter.R

Customize lint message for equals_na_linter()

---

R/object_name_linter.R
R/shared_constants.R

Shared between `object_name_linter()` and `return_linter()`.

Move shared constant to the right file

---

R/paste_linter.R
man/paste_linter.Rd

The description breaks in the middle because of an empty line.
cf. https://lintr.r-lib.org/dev/reference/paste_linter.html

Fix `paste_linter()` Rd docs

---

.lintr
R/utils.R
R/zzz.R
man/default_undesirable_functions.Rd
man/todo_comment_linter.Rd

Have been getting some spurious diffs vs. `main` on this. Is anyone else seeing it? I'm a bit surprised because the `default*` objects are coming from `modify_defaults()`, which uses `platform_independent_order()` already:
https://github.com/r-lib/lintr/blob/fdbb9bfa1ea868ad66c6fe9a30b4ae872c03f56e/R/with.R#L59
Maybe this is a call to improve `platform_independent_order()`? That's pretty rudimentary indeed:
https://github.com/r-lib/lintr/blob/fdbb9bfa1ea868ad66c6fe9a30b4ae872c03f56e/R/utils.R#L206-L207

Sort default_undesirable docs robustly

---

.github/workflows/repo-meta-tests.yaml

Based on https://github.com/r-lib/lintr/actions/runs/7454773326 failure.
I don't see how #2494 is related, so I assume what's happened is {roxygen2} fell out of the recursive dependencies of our deps with some recent package update. TBH I was surprised this entry in GHA wasn't needed when first implemented.

Ensure roxygen2 available for GHA

---

DESCRIPTION
R/get_source_expressions.R
R/ids_with_token.R
R/is_lint_level.R
R/lint.R
R/trailing_blank_lines_linter.R
R/utils.R
R/with.R
man/get_r_string.Rd
man/get_source_expressions.Rd
man/ids_with_token.Rd
man/is_lint_level.Rd
man/lint.Rd
man/linters_with_defaults.Rd
man/trailing_blank_lines_linter.Rd

Per discussion here:
https://github.com/r-lib/withr/issues/256
This is an expected failure, and it seems `local_tempfile()` never really behaved as I'd've thought in examples anyway (namely, to clean up the file after each example runs).
There are ways to keep using {withr} if we really want, e.g. I think adding a line to set `withr.hook_source` option in the `check-all-examples` GHA would work, but now I think it's best to just stick with base functionality for these examples.

Remove local_tempfile() usage in examples following breakage by withr 3.0.0

---

cran-comments.md
tests/testthat/test-get_source_expressions.R

Coming from changes to the parser in R-devel
Closes #2527

Fix failing test on R-devel

---

R/addins.R

Closes #2525
Probably I don't understand how add-ins are invoked, but it seems this approach should work & is much simpler.
cc @HaHeho -- are you able to test if this works?

Remove custom linting logic from addins

---

R/undesirable_function_linter.R
man/undesirable_function_linter.Rd

Closes #2532. No sense keeping specific functions named here, which might change over time; better to just link `?default_undesirable_functions`, which is already done.

Remove reference to specific functions in help

---

DESCRIPTION

Since CRAN version is `3.1.2`, the default branch's "devel" version is lagging CRAN version.

Bump package version to devel

---

.github/workflows/R-CMD-check.yaml

> `next` corresponds to the next version of R, either R-patched, or R-alpha, R-beta, R-rc, or R-prerelease

Get rid of outdated comments from GHA for R CMD check

---

NEWS.md
R/object_name_linter.R
R/shared_constants.R
tests/testthat/test-object_length_linter.R
tests/testthat/test-object_name_linter.R

Closes #1926
`object_length_linter()` change comes "for free". We could ignore this with some more effort, but I think the change is also welcome.

Skip rlang name injections

---

NEWS.md
R/indentation_linter.R
tests/testthat/test-indentation_linter.R

Closes #2550.
The lint still has `column_number==0L`, show we bump that to `1L` as well?
```
lint(text = sprintf("if (TRUE) {\n%sFALSE\n}", strrep(" ", 0:5)), linters = indentation_linter())
<text>:2:0: style: [indentation_linter] Indentation should be 2 spaces but is 0 spaces.
FALSE
^~
<text>:5:1: style: [indentation_linter] Indentation should be 2 spaces but is 1 spaces.
FALSE
^~
<text>:11:3: style: [indentation_linter] Indentation should be 2 spaces but is 3 spaces.
FALSE
^
<text>:14:4: style: [indentation_linter] Indentation should be 2 spaces but is 4 spaces.
FALSE
~^
<text>:17:5: style: [indentation_linter] Indentation should be 2 spaces but is 5 spaces.
FALSE
~~^
```

don't allow ranges[1]==0

---

DESCRIPTION

- On main:
```r
downlit:::autolink_curly("{lintr}")
#> "<a href='https://github.com/r-lib/lintr'>lintr</a>"
```
- On current branch:
```r
downlit:::autolink_curly("{lintr}")
#> "<a href='https://lintr.r-lib.org'>lintr</a>"
```

Change URL order in DESCRIPTION to be pkgdown-friendly

---

R/utils.R
man/get_r_string.Rd

In pkgdown, this output is right below the code.
In RStudio IDE, users can just click on "Run examples", and it will show the output.
Everywhere else, the users can execute the code and see the outputs. I don't think we need to embed the outputs here.
---
Another issue is that styler keeps restyling this code, which needs to be reverted:
```r
styler::style_text('get_r_string(expr_as_xml4.0, "expr[2]") # "a\\b"')
#> get_r_string(expr_as_xml4.0, "expr[2]") # "a\b"
```

Remove outputs from roxygen examples

---

NEWS.md
R/scalar_in_linter.R
inst/lintr/linters.csv
man/configurable_linters.Rd
man/linters.Rd
man/scalar_in_linter.Rd
tests/testthat/test-scalar_in_linter.R

Make scalar_in_linter configurable to allow projects to define additional %in% style functions like %notin%.

Make `scalar_in_linter()` configurable

---

NEWS.md
R/expect_identical_linter.R
tests/testthat/test-expect_identical_linter.R

Handle comparison to negative non-integer in expect_identical_linter

---

R/make_linter_from_regex.R
tests/testthat/test-ci.R

Remove usage of internal function in CI tests

---

.github/workflows/R-CMD-check.yaml

Since neither the vignette builder (knitr) nor the testing framework (testthat) is available for this R version: they (via dependency `{evaluate}`) need `>= R 4.0`.

Remove `R 3.6` checks from CI

---

DESCRIPTION
NEWS.md
tests/testthat/test-lint_package.R

Bump required R version

---

.lintr
NEWS.md
R/exclude.R
R/lint.R
R/path_utils.R
R/settings_utils.R
R/use_lintr.R
tests/testthat/test-cache.R
tests/testthat/test-lint.R
tests/testthat/test-lint_dir.R
tests/testthat/test-normalize_exclusions.R
tests/testthat/test-settings.R
tests/testthat/test-use_lintr.R

Minor annoyance, but thought I'd share the PR in case there is interest
it is just to fix a minor inconsistency between Unix and Windows.
```r
x <- lint(path)
names(x)
```
This basically just changes that and makes sure that the names of the linted object are the same on both platforms with forward slash

Normalize output to Forward slash

---

vignettes/creating_linters.Rmd
vignettes/lintr.Rmd

I think this is a good pattern to follow also in our vignettes.
Ref: https://r-pkgs.org/vignettes.html#metadata

Leave out some vignette metadata

---

_pkgdown.yaml

Currently, we are dumping way too many functions in the [meta-tooling section](https://lintr.r-lib.org/dev/reference/index.html#meta-tooling). This increases the possibility of the users missing out on important functions, like `all_linters()` or `default_linters()`.

Add new section for grouped linters in website reference index

---

R/actions.R
R/methods.R
tests/testthat/test-ci.R

If I locally render the site, I see:
``` r
library(lintr)
withr::local_options(lintr.rstudio_source_markers = FALSE)
withr::local_envvar(list(GITHUB_ACTIONS = "true"))
tmp <- withr::local_tempfile(lines = "x <- 1:nrow(y)")
withr::local_envvar(list(IN_PKGDOWN = "true"))
lint(tmp)
#> /private/var/folders/xr/v_vddzvs33q5wg7jv9mr__4h0000gn/T/RtmpwfSzjb/filedd1064e6f6e8:1:6: warning: [seq_linter] Use seq_len(nrow(...)) instead of 1:nrow(...), which is likely to be wrong in the empty edge case.
#> x <- 1:nrow(y)
#>      ^~~~~~~~~
withr::local_envvar(list(IN_PKGDOWN = "false"))
lint(tmp)
#> ::warning file=/private/var/folders/xr/v_vddzvs33q5wg7jv9mr__4h0000gn/T/RtmpwfSzjb/filedd1064e6f6e8,line=1,col=6::file=/private/var/folders/xr/v_vddzvs33q5wg7jv9mr__4h0000gn/T/RtmpwfSzjb/filedd1064e6f6e8,line= …
```

Don't include GHA log output in pkgdown website

---

.github/workflows/R-CMD-check-hard.yaml
.github/workflows/R-CMD-check.yaml
NEWS.md
R/methods.R
tests/testthat/test-methods.R

Closes #2640
``` r
library(lintr)
lint(text = "x <- 1L", linters = all_linters())
#> ℹ No lints found.
```
<sup>Created on 2024-08-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Print a message when no lints found

---

NEWS.md
R/methods.R

fix #2645 
Basically, this checks for clickable hyperlinks. I also saw that some code was still hidden behind `requireNamespace("cli")` but that is no longer required since cli is imported.
To my great surprise, this works out of the box in Positron ! for `lintr::lint_package()`
Before, there were no hyperlinks (lintr 3.1.2)
Lmk if you'd like me to add NEWS for this!

Support clickable hyperlinks

---

paper/paper.Rmd
paper/paper.md

There is an issue in [generating PDF](https://github.com/openjournals/joss-reviews/issues/7171#issuecomment-2327379155) of the paper during review because affiliations are missing for some authors.
There is still one missing affiliation that I can't find.

Add missing affiliations for authors

---

R/redundant_equals_linter.R
man/redundant_equals_linter.Rd

Include `{data.table}` example in `redundant_equals_linter()` docs

---

NEWS.md
R/commented_code_linter.R
tests/testthat/test-commented_code_linter.R

Closes #2671
The PR removes pipes from the end of `extracted_code` when checking parsability of code. A test to check that a lint is detected on commented lines ending with a pipe (which are otherwise parsable) are indeed detected.
This solves a common false negative occurrence in, for example, data wrangling
``` r
mtcars |>
dplyr::summarise(m = mean(wt))
```
The above snippet detect no commented code lints, but changes in this PR would lead to a commented code linter being detected

Remove pipe on end of commented code prior to checking parsability

---

.Rbuildignore

Just noticed this wound up on CRAN:
https://github.com/cran/lintr/blob/945dc7b6e6f8cbfcdeafa93fe2acc0eaa0645da5/tests/testthat/testthat-problems.rds

Don't package testthat-problems.rds

---

R/extract.R
R/get_source_expressions.R
R/lint.R
R/utils.R

A small step towards lint clean-up that will eventually be needed by https://github.com/r-lib/lintr/pull/2676.

Add utils to check for lint and error classes

---

R/class_equals_linter.R
tests/testthat/test-class_equals_linter.R

Per experience here:
https://github.com/Rdatatable/data.table/pull/6603#discussion_r1854842225
I think it's good to more strongly recommend `is()` only for S4 classes.

Emphasize S3-S4 difference in recommendation for how to fix class_equals_linter()

---

DESCRIPTION

lintr uses the `...names()` function via backports on R versions <4.1.0. This function was [added](https://github.com/r-lib/backports/blob/main/NEWS.md#backports-140) to backports in version 1.4.0, so older versions of backports don't work. This PR bumps up the minimum version of backports in the DESCRIPTION.

Bump minimum backports version to ensure support for ...names()

---

DESCRIPTION
NEWS.md

Again merging without review to keep `main` & CRAN builds of the package distinct

Bump to dev version

---

NEWS.md
R/lint.R
man/lint-s3.Rd

Another post-release progression of deprecation

Remove linter= argument of Lint()

---

NEWS.md
R/is_lint_level.R

Found by our internal typo linter

Two typos: Github->GitHub, unneccessary->unnecessary

---

R/linter_tags.R

The outer `{` covers the tag, we still need the inner `{` to get "glue evaluation" of that variable, otherwise we get these errors:
```
✖ linter_tag_docs.R:89: @evalRd failed to evaluate.
Caused by error in `rd_linters()`:
! No linters found associated with tag tag_name.
✖ lintr-deprecated.R:5: @evalRd failed to evaluate.
Caused by error in `rd_tags()`:
! Tags are required, but found none for `linter_name()`.
```

Add missing nested '{}' in cli evaluation

---

NEWS.md
R/lintr-deprecated.R
inst/lintr/linters.csv
man/deprecated_linters.Rd
man/linters.Rd
man/lintr-deprecated.Rd
tests/testthat/test-consecutive_assertion_linter.R
tests/testthat/test-quotes_linter.R
tests/testthat/test-unneeded_concatenation_linter.R
tests/testthat/test-whitespace_linter.R

Follow-up to #2733.
After this, there are no more (currently) deprecated linters, so the documentation page gets a bit funny since there are no associated linters. Hence #2745 and #2744 -- I think it makes sense to keep the stub around (certainly while we're still in dev), and it's not unlikely that we'll deprecate something else before the next release.
NB: This is currently based against #2745.

Progress deprecation of 4 more linters warning since last release

---

NEWS.md
R/unnecessary_nesting_linter.R
tests/testthat/test-unnecessary_nesting_linter.R

Exempt OP-LAMBDA the same as FUNCTION in unnecessary_nesting_linter

---

DESCRIPTION

Since {cli} is in `Imports:` this is redundant (this might have been made obsolete when adding {cli} recently).

Remove duplicate {cli} dependency for development

---

NEWS.md
R/implicit_integer_linter.R
tests/testthat/test-implicit_integer_linter.R

implicit_integer_linter(allow_colon=TRUE) ignores negative inputs

---

tests/testthat/test-methods.R
tests/testthat/test-rstudio_markers.R

These tests have been omitting uncaught output for some time (probably since #2643):
https://github.com/r-lib/lintr/actions/runs/13335295688/job/37249044522
Better to capture this output intentionally, vs. let it bubble up.

Capture emitted output as a test

---

NEWS.md
R/missing_argument_linter.R
tests/testthat/test-missing_argument_linter.R

Close #2741
Progress again on #2737

Ignore comments in empty call like foo() in missing_argument_linter

---

NEWS.md
R/unnecessary_nesting_linter.R
tests/testthat/test-unnecessary_nesting_linter.R

Closes #2245
Also further progress on #2737.

Skip when 2nd expression under if() is an '=' assignment in unnecessary_nesting_linter()

---

NEWS.md
R/linter_tags.R
R/lintr-deprecated.R
inst/lintr/linters.csv
man/deprecated_linters.Rd
man/linters.Rd
man/lintr-deprecated.Rd
tests/testthat/test-consecutive_assertion_linter.R
tests/testthat/test-quotes_linter.R
tests/testthat/test-unneeded_concatenation_linter.R
tests/testthat/test-whitespace_linter.R

Another option is to special-case `deprecated`, but I think this approach is OK.
NB: this PR is based against #2744 for now.

Allow that a tag has no associated linters (esp. "deprecated")

---

NEWS.md
R/unnecessary_nesting_linter.R
R/utils.R
tests/testthat/test-unnecessary_nesting_linter.R

Closes #2316.
Also
- Add an early return to `get_r_string()`, which might get called many times with empty inputs
- Avoid `//expr` XPath

Specific advice in unnecessary_nesting_linter metadata

---

.github/workflows/test-coverage.yaml

Ran `usethis::use_github_action('test-coverage')`.
Hopefully this resolves the issues observed in #2770 and #2775, I continue to see something about rate-limiting in the GHA logs, e.g.
https://github.com/r-lib/lintr/actions/runs/13464477182/job/37627166271
```
Run covr::codecov()
Request failed [429]. Retrying in 1.7 seconds...
Request failed [429]. Retrying in 1 seconds...
$detail
[1] "Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: [16](https://github.com/r-lib/lintr/actions/runs/13464477182/job/37627166271#step:5:17)98s."
```

update to current covr GHA

---

NEWS.md
R/paste_linter.R
man/paste_linter.Rd

Closes #2675.
First I confirmed the linter is working in the intuitive way:
```
lint(text = "paste('a', 'b', sep = '/')", linters = paste_linter(allow_file_path="never"))
lint(text = "paste('a', 'b', sep = '/')", linters = paste_linter(allow_file_path="always"))
lint(text = "paste('a', 'b', sep = '/')", linters = paste_linter(allow_file_path="double_slash"))
lint(text = "paste0('a//b/', 'c')", linters = paste_linter(allow_file_path="never"))
```

Fix description of paste_linter(allow_file_path=)

---

NEWS.md
R/methods.R
R/return_linter.R
tests/testthat/test-return_linter.R

Closes #2616. Progress on #2737.

Land on function body more robustly in return_linter()

---

vignettes/lintr.Rmd

The exposition is slightly off now that printing empty lint objects gives a message "No lints found".

Adjust to "no lints found" output in lintr vignette exposition

---

.github/workflows/test-coverage.yaml

Bad dependabot! tsk tsk
#2782 updated the version but failed to catch that the argument names were changed.
As noted here: https://github.com/r-lib/actions/pull/984

Fix updated argument names after updating codecov GHA

---

R/lintr-package.R
tests/testthat/test-linter_tags.R

Closes #933.
I wrote a few different approaches for constructing the difference between the csv on disk & the expected output, nothing seemed particularly clean, but feel free to chime in if you've got a preference. Fundamentally it's challenging that `write.csv()`/`read.csv()` don't support list columns, hence a need to massage a bit.

add a test of available_linters(packages=)

---

NEWS.md
R/shared_constants.R
tests/testthat/test-object_length_linter.R
tests/testthat/test-object_name_linter.R

Closes #1665. Also progress on #2737

Catch bad naming style (and length) in assign() + setGeneric() usages

---

.dev/defunct_linters_test.R
.github/workflows/repo-meta-tests.yaml

Closes #2734.
Pretty simple. I think maybe eventually we'll move the tests about "tags in linters.csv match man/*" here too. But this is enough for now.

New meta test about defunct linters

---

NEWS.md
R/declared_functions.R
tests/testthat/test-object_name_linter.R

Closes #2507.
Ignoring `->`-assigned generics because it's very awkward to write them:
```r
(function(x) UseMethod('foo')) -> foo
```

Include =-assigned generics when checking object name/length

---

R/cyclocomp_linter.R
R/settings.R
R/with.R
tests/testthat/test-cyclocomp_linter.R
tests/testthat/test-get_source_expressions.R
tests/testthat/test-linter_tags.R
tests/testthat/test-settings.R
tests/testthat/test-use_lintr.R
tests/testthat/test-with.R

Closes #2777
Two notable changes accompany this:
- Rather than _error_ up-front if {cyclocomp} is unavailable, we _warn_ & return a "dumb" linter that just always & immediately finds no lints.
- `linters_with_tags()` (_via_ `call_linter_factory()`) _warns_ instead of _errors_ when a linter fails to build. Again we return the "dumb" linter in this case. This is not strictly needed thanks to only warning from the factory, but I think it's a better design anyway.
Mostly in tests I've opted anyway for `skip()`s, rather than an awkward construct where we optionally `expect_warning()`, or swap between `expect_warning()`/`expect_no_warning()`, or ...
This exercise also flushed out some more tests that are implicitly reading our main project .lintr file, fixing which increases their hermeticity.

Move the cyclocomp namespace check into the factory

---

R/pipe_return_linter.R
man/pipe_return_linter.Rd

Not sure why this is uncaught till now, AFAICT this has been warning since >2 years ago (?)
https://github.com/r-lib/roxygen2/issues/1492#issuecomment-2701698220
Still the update is an improvement, I think.

Rework ?pipe_return_linter to avoid roxygen issue

---

R/backport_linter.R
man/backport_linter.Rd

While thinking about #1974, I noticed some features of `backport_linter()` were not explicitly documented. This minor PR aims to help discoverability of this useful feature.

Make `backport_linter(r_version = )` default and options more explicit

---

.lintr
R/methods.R
R/object_usage_linter.R
R/settings.R
R/settings_utils.R
R/trailing_blank_lines_linter.R
R/utils.R
R/zzz.R

Drop our internal %|||% helper

---

R/condition_call_linter.R
tests/testthat/test-condition_call_linter.R

Apply condition_call_linter() only on string literals

---

R/literal_coercion_linter.R
R/xml_utils.R
tests/testthat/test-literal_coercion_linter.R

Split off from #2822. Closes #2824 . Progress on #2737.
NEWS omitted for now, I think it makes sense to just defer it to the end of this incoming change split off from #2822.

Improve robustness to comments in literal_coercion_linter

---

NEWS.md
R/coalesce_linter.R
tests/testthat/test-coalesce_linter.R

This PR fixes a bug where `coalesce_linter()` incorrectly warned for if statements without else clauses:
```r
if (!is.null(x)) x
#> Use x %||% y instead of if (!is.null(x)) x else y.
if (!is.null(x)) x  # no warning
```
The XPath query had two branches for detecting coalesce patterns. The first branch (for `is.null` patterns) correctly checked for an ELSE node, but the second branch (for `!is.null` patterns) was missing this check, causing false positives. Added one line (`and parent::expr/following-sibling::ELSE`) to ensure both branches only match if-else statements, not plain if statements. Includes 3 regression tests.
Fixes #2936.

Fix false positive for null coalescing without else clause

---

R/expect_lint.R

`expect_success()` and `expect_failure()` now test that you have exactly one success/failure and zero failures/successes. I can't quite figure out why the tests are still failing here; maybe it's something to do with recycling? I'm happy to help but I unfortunately I don't know enough about the lintr internals to figure out what's going wrong here.
We're planning to submit testthat to CRAN on Nov 10.

Partial fix for upcoming testthat release
