inst/syntastic/lintr.vim
Fixes bug jimhester/lintr#45 .
=> Fixed bug that caused vim syntatic plugin not to work properly in windows

NEWS.md, R/lint.R, tests/testthat/test-exclusions.R
=> Respect "# nolint" comments with caching

tests/testthat/test-exclusions.R
=> clear cache only for single file used in test

README.md
=> Mention name of default config file

README.md
Please feel free to change wording. Adding this as a supported function to the package is probably too much.
Ref: https://github.com/jimhester/lintr/issues/73#issuecomment-90927745
=> Simplify getting started

R/assignment_linter.R, README.md
Creating initial file doesn't work with current CRAN version of lintr.
=> State version requirements

README.md
=> Fix spacing in default .lintr file

.travis.yml, DESCRIPTION, R/expect_lint.R, README.md, wercker.yml
Unfortunately this function is currently un-exported. :(
=> Use testthat:::expect

NEWS.md, R/closed_curly_linter.R, tests/testthat/test-closed_curly_linter.R
=> close #113: Allow closing parens or comma after closing curly brackets

.gitignore, lintr.Rproj, tests/testthat/checkstyle.xml
Sorry if this is an inappropriate/annoying request, since it is more programmer style. But can you add an Rproject file to this? It makes is easier for anyone working in Rstudio to contribute.
=> Add Rstudio project

NEWS.md
=> Update version to be 1.0.2.9000

README.md
This PR makes the recommended method easier to find, and adds a link to a package using it.
One thing I'd also like to add, but maybe by a separate PR, is a TOC in order to make it easier to navigate to the available linters and project setup.
=> CI setup docs

NEWS.md, R/utils.R, R/zzz.R
=> Set github token from env

README.md
=> Add VIM/ALE integration to README (#263)

README.md
This PR adds introduction to enabling lintr in VSCode.
=> Add VSCode to README.md

R/methods.R, tests/testthat/test-methods.R
=> treat tabs as spaces in print.lint

.Rbuildignore, DESCRIPTION, R/get_source_expressions.R
=> Resolve check warnings and notes

.lintr
Closes #599 
Package already passes, just need to enable it
=> enable closed_curly_linter

.lintr, R/function_left_parentheses.R, R/object_usage_linter.R
Closes #600 
We are already compliant, just need to enable
=> enable object_length_linter

NEWS.md, R/sprintf_linter.R, tests/testthat/test-sprintf_linter.R
=> Make sprintf_linter capture warnings

R/utils.R, tests/testthat/test-equals_na_linter.R
Missing from this PR: coverage of `rot` which is handled in #629
=> coverage for utils.R

R/get_source_expressions.R
=> temporarily set LANGUAGE in get_source_expressions

tests/testthat/test-expect_lint.R
#650 didn't exactly work as intended.
=> fix expect_lint coverage test

NEWS.md, R/line_length_linter.R, tests/testthat/test-line_length_linter.R
fixes #681
also added a regression test.
=> fix duplicate line_length lints.

README.md
- adding example of ignored linter
- outlining example config file section with header so it's easier to find
=> Minor update to readme 

.github/workflows/lint.yaml
=> remove superfluous GHA lint workflow on push to any branch

tests/testthat/test-normalize_exclusions.R
s/;/\n/
makes lint_package() lint free @ master
=> delint test-normalize_exclusions.R

R/line_length_linter.R
quick internal change. actually i think we should do this lint on the whole file too, but that is less trivial
=> nchar() is vectorized, no need for vapply

README.md
Fix https://github.com/jimhester/lintr/issues/430
=> How to run lintr (in R, and from command line)

tests/testthat/test-sprintf_linter.R
=> fix version condition in sprintf linter tests

.dev/compare_branches.R, NEWS.md, R/zzz.R, tests/testthat/test-settings.R
=> with_defaults removes newlines before processing names

R/ids_with_token.R, R/zzz.R, man/ids_with_token.Rd, man/with_defaults.Rd
Fixed a couple of small typo's in the comments for zzz.R and ids_with_token.R
=> Fix small typos in zzz.R and ids_with_token.R

NEWS.md
=> Add news item for lint(text=)

README.md
=> typo. closes #805

.github/workflows/R-CMD-check.yaml, NEWS.md
since the release of R 4.1 the workflow matrix is slightly out-of-date (not checking against R 3.6, but keeping the check for R 3.3). this PR should re-align the combinations with the latest minor R release.
=> R cmd gha update

README.md, man/checkstyle_output.Rd
Closes #828 
Skipped the VS marketplace link is a false positive; filed https://github.com/r-lib/urlchecker/issues/15
=> Address URL redirects

DESCRIPTION
Following @russHyde's [suggestion](https://github.com/jimhester/lintr/issues/824#issuecomment-875375655).
@MichaelChirico @renkun-ken @jimhester 
Please let me know if you're okay with this. Thanks.
=> Add @renkun-ken, @MichaelChirico and @AshesITR to Authors

NEWS.md, R/exclude.R, tests/testthat/dummy_projects/project/mismatched_starts_ends.R, tests/testthat/dummy_projects/project/one_start_no_end.R, tests/testthat/test-exclusions.R
=> 860: add line numbers in the "starts do not match ends" error message

.github/workflows/R-CMD-check.yaml, .github/workflows/lint-changed-files.yaml, .github/workflows/lint.yaml, .github/workflows/test-coverage.yaml, DESCRIPTION, codecov.yml
Attempt to fix the build failures pertaining to missing pdflatex.
hopefully fixes #896
=> Create fresh R-CMD-check.yaml from use_tidy_github_actions()

R/methods.R
=> re-name symbol duped with call

R/package_hooks_linter.R, man/package_hooks_linter.Rd
=> more explicit in package_hooks_linter.Rd

tests/testthat/test-knitr_formats.R
=> improve robustness of knitr_formats test

tests/testthat/test-rstudio_markers.R
Closes #925
Added a TODO to revisit sometime soon, perhaps even before release.
=> dont use new lines= argument yet

R/T_and_F_symbol_linter.R, R/assignment_linter.R, R/expect_true_false_linter.R
=> narrower lines

R/expect_comparison_linter.R, R/expect_length_linter.R, R/expect_s3_class_linter.R, R/expect_type_linter.R, tests/testthat/test-expect_comparison_linter.R, tests/testthat/test-expect_length_linter.R, tests/testthat/test-expect_s3_class_linter.R, tests/testthat/test-expect_type_linter.R
=> account for when arguments cant be used in rec. replacement

.dev/compare_branches.R
I had to fiddle around a little bit with this to get it to work for #397, maybe you'll find these useful/sensible as well:  
- 105: make sure `if(is.na(...`  always evaluates to `logical(1)`
- 153: actually use parameter "sample_size"
- 349f: more fault-tolerant loop over linters
- 370: flush warnings to terminal at the end
=> suggestions for compare_branches

R/linter_tags.R
=> stricter requirements in doc generation

R/function_brace_linter.R
=> function_brace_linter is a 'style' linter

NEWS.md, R/function_brace_linter.R, R/missing_package_linter.R, tests/testthat/test-missing_package_linter.R
=> Missing package symbol

R/lint.R, man/lint_package.Rd
=> document which directories lint_package searches

NEWS.md, R/unreachable_code_linter.R, tests/testthat/test-unreachable_code_linter.R
=> unreachable_code_linter() doesnt lint after process$stop()

README.md
Suggested by https://github.com/r-lib/lintr/issues/766#issuecomment-1074788133
I recently set up supler-linter in https://github.com/rocker-org/rocker-versioned2 and it seems to be working well.
=> Add note about super-linter

R/object_usage_linter.R, R/seq_linter.R, R/utils.R
Plus other minor cleanup of the helpers in R/utils.R
=> Don't define backports if not needed

NEWS.md, R/object_usage_linter.R, tests/testthat/test-object_usage_linter.R
=> simplify object_usage helper function, fix error

NEWS.md, R/yoda_test_linter.R, tests/testthat/test-yoda_test_linter.R
Closes #979 
Based against #1069 for now.
=> customize yoda_test_linter message for placeholder tests

NEWS.md, R/yoda_test_linter.R, tests/testthat/test-yoda_test_linter.R
Closes #1066 
Based against #1068 for now
=> handle pipe-terminal tests in yoda linter

NEWS.md
must have been a sloppy merge of the PR chain slipped by us
=> duplicate bullet in NEWS

NEWS.md, R/undesirable_function_linter.R, tests/testthat/test-undesirable_function_linter.R
fixes #1050
added a regression test and did some mild XPath refactoring
=> ignore $symbol in undesirable_function_linter

tests/testthat/test-get_source_expressions.R, tests/testthat/test-ids_with_token.R, tests/testthat/test-with_id.R
=> add tests for with_id and ids_with_token

NEWS.md, R/undesirable_operator_linter.R, R/zzz.R, tests/testthat/test-undesirable_operator_linter.R
=> explain undesirable functions in lint message, remove "return" from all_undesirable_functions

R/cyclocomp_linter.R
Noticed `is_lint_level()` belongs & cleaned up some other things while we're at it
=> clean up cyclocomp_linter

R/sprintf_linter.R
hacking away at the big pile of `implicit_integer_linter()` hits
=> implicit integers in sprintf_linter

R/T_and_F_symbol_linter.R, R/xp_utils.R, man/xml_nodes_to_lints.Rd
=> offset= refactored to match_after_end=

R/implicit_integer_linter.R
=> use xpath for implicit_integer_linter

R/zzz.R, man/default_undesirable_functions.Rd
=> dont link to non-dependency packages in docs

R/tree-utils.R
=> remove unused internal functions

R/get_source_expressions.R
=> refactor fix_tab_columns to reduce cyclo complexity

R/get_source_expressions.R, R/missing_argument_linter.R, R/missing_package_linter.R, R/namespace_linter.R, R/single_quotes_linter.R, tests/testthat/test-get_source_expressions.R
=> name source_expression$file_lines for file-level expression

R/linter_tags.R
=> Reduce cyclomatic complexity of available_linters

NEWS.md
=> add a note about how to recover the old behavior for undesirable return()

R/lint.R
Part of #1186 
More could be done here but this gets us under the 15 threshold
=> add a helper to lint_dir for simplicity

NEWS.md
bullets should be easier to read
=> tidy item about removed linters

R/expect_identical_linter.R, R/expect_length_linter.R
Part of #1199 
Vectorize for `expect_length_linter()`
=> move logic to factory for expect_identical and expect_length linters

R/conjunct_test_linter.R
=> conjunct_test_linter xpath to factory; vectorize message

.lintr, R/cache.R, R/lint.R
=> Reduce cyclocomp of `lint()` to <= 15

R/brace_linter.R, R/class_equals_linter.R
Part of #1199 
Also vectorized the message extraction for `class_equals_linter()`
=> logic to factory for brace_linter & class_equals_linter

R/closed_curly_linter.R, R/commas_linter.R, R/comment_linters.R, R/condition_message_linter.R, tests/testthat/test-condition_message_linter.R
Part of #1199 
`condition_message_linter` logic is vectorized & added a test that its working
=> linter logic to factory in comment, condition_message linters

R/extraction_operator_linter.R, R/fixed_regex_linter.R, R/ifelse_censor_linter.R, tests/testthat/test-extraction_operator_linter.R
Part of #1199
`ifelse_censor_linter()` is a bit less trivial for vectorization. there might be a simpler way.
=> move xpath to factor for extraction_operator, fixed_regex, ifelse_censor linters

R/infix_spaces_linter.R, R/inner_combine_linter.R, R/literal_coercion_linter.R, R/missing_argument_linter.R, R/missing_package_linter.R, R/namespace_linter.R, R/nested_ifelse_linter.R, R/numeric_leading_zero_linter.R, R/object_name_linters.R, R/object_usage_linter.R, R/outer_negation_linter.R
=> move logic to factory for linters ^[i-o]

R/paren_body_linter.R, R/paren_brace_linter.R, R/paste_linter.R, R/pipe_call_linter.R, R/pipe_continuation_linter.R, R/redundant_ifelse_linter.R
=> another batch of pulling static linter parts to factory

R/consecutive_stopifnot_linter.R, R/cyclocomp_linter.R, R/duplicate_argument_linter.R, R/equals_na_linter.R, R/expect_comparison_linter.R, tests/testthat/test-cyclocomp_linter.R
Part of #1199 
Vectorized message in `expect_comparison_linters()`
=> xpath to factory for consecutive_stopifnot, equals_na and expect_comparison_linters

R/T_and_F_symbol_linter.R, R/unneeded_concatenation_linter.R, R/unreachable_code_linter.R, R/unused_import_linter.R, R/yoda_test_linter.R
Part of #1199
Last of the series (unless I missed something -- very possible :sweat_smile:)
=> finish moving static logic to factories

R/sprintf_linter.R, R/utils.R, tests/testthat/test-sprintf_linter.R
fixes #1249
added a regression test
=> support multi-line calls in sprintf() again

R/sprintf_linter.R, tests/testthat/test-sprintf_linter.R
=> support named fmt argument and skip linting calls with dots

.github/workflows/test-package-vigilant.yaml, R/expect_null_linter.R, R/expect_s3_class_linter.R, R/expect_type_linter.R
fixes #1263 
first step is try to get a failure from GHA for the warning situation
=> create vigilant test workflow

R/yoda_test_linter.R
=> vectorize lint_message in yoda_test_linter

R/unused_import_linter.R, tests/testthat/test-unused_import_linter.R
=> ignore symbols in library calls

R/package_hooks_linter.R
=> vectorize lint_message for some lints in package_hooks_linter

R/undesirable_function_linter.R, R/utils.R
=> stats::setNames

tests/testthat/test-fixed_regex_linter.R
Just to remove the noise in reviewing while #1175 is pending
=> code-ify comments to de-lint

R/undesirable_operator_linter.R, tests/testthat/test-undesirable_operator_linter.R
=> vectorize undesirable_operator lint_message, add a test

tests/testthat/test-dir_linters.R, tests/testthat/test-expect_lint.R
=> add a comment, robust paths in test_path()

NEWS.md, R/unneeded_concatenation_linter.R, man/unneeded_concatenation_linter.Rd, tests/testthat/test-unneeded_concatenation_linter.R
=> unneeded_concatenation_linter improves accuracy, gains argument for c(x) lints

inst/lintr/linters.csv, man/configurable_linters.Rd, man/linters.Rd, man/unneeded_concatenation_linter.Rd
=> add configurable tag to unneeded_concatenation_linter

NEWS.md, R/get_source_expressions.R, man/get_source_expressions.Rd, tests/testthat/test-get_source_expressions.R
=> Deprecate find col

tests/testthat/test-object_usage_linter.R
=> use xml2 in test

NEWS.md, R/comment_linters.R, R/extract.R, tests/testthat/test-get_source_expressions.R, tests/testthat/test-trailing_blank_lines_linter.R
fixes #1406 
fixes #743 
fixes #879
=> prioritize plain R code over knitr

vignettes/editors.Rmd
This allows me to use .lintr files for configuration using vim ALE
=> adds workaround to using .lintr files with vim ALE

NEWS.md, R/extract.R, tests/testthat/test-get_source_expressions.R, tests/testthat/test-trailing_blank_lines_linter.R
=> return non-empty file_lines even if no R source is present

NEWS.md, R/exclude.R, tests/testthat/test-exclusions.R
=> fix file exclusion logic in lint_dir()

NEWS.md, R/with.R, tests/testthat/test-linter_tags.R, tests/testthat/test-with.R
=> add modify_defaults to deprecation warning of with_defaults

vignettes/continuous-integration.Rmd, vignettes/lintr.Rmd
Closes #1460
h/t ` urlchecker::url_check()`
=> Update outdated URLs

R/vector_logic_linter.R, man/vector_logic_linter.Rd
=> another note re: edge cases in | vs ||

_pkgdown.yml
Related to https://github.com/r-lib/lintr/issues/824
=> Add blog post to the website

DESCRIPTION
Done via `usethis::use_tidy_description()`
=> Follow tidyverse conventions for `DESCRIPTION`

DESCRIPTION
cf. https://github.com/r-lib/lintr/pull/1479#issuecomment-1197655701
Usually, this would also be mentioned in `NEWS.md`. 
But I don't see any previous entries about new authors, so I have skipped it.
Let me know if I should add it.
=> Adds me as author in `DESCRIPTION` file

tests/testthat/test-namespace_linter.R
Follow the same pattern we are following in other tests.
=> DRY in test for ns linter

.github/workflows/R-CMD-check.yaml, .github/workflows/lint-changed-files.yaml, .github/workflows/lint.yaml
cf. https://github.com/r-lib/actions/issues/606
=> Use latest Ubuntu in GHA workflows

R/lint.R, man/lint.Rd
=> Update ellipsis parameter docs for `lint()` et al

DESCRIPTION, NEWS.md, tests/testthat/checkstyle.xml
https://github.com/r-lib/lintr/issues/1524
=> Bump to devel

R/object_usage_linter.R
=> `object_usage_linter()` sets `useFancyQuotes=FALSE`

R/backport_linter.R, R/cache.R, R/comment_linters.R, R/declared_functions.R, R/duplicate_argument_linter.R, R/equals_na_linter.R, R/exclude.R, R/expect_lint.R, R/expect_named_linter.R, R/extract.R, R/get_source_expressions.R, R/inner_combine_linter.R, R/line_length_linter.R, R/linter_tags.R, R/literal_coercion_linter.R, R/make_linter_from_regex.R, R/methods.R, R/missing_argument_linter.R, R/namespace.R, R/object_usage_linter.R, R/redundant_ifelse_linter.R, R/settings.R, R/spaces_left_parentheses_linter.R, R/trailing_blank_lines_linter.R, R/utils.R, R/vector_logic_linter.R, R/with.R, R/zzz.R
I have reverted some changes where `{styler}` couldn't preserve the deliberate alignments, or changed the positions of comments related to ignoring lint, etc.
=> Formatting changes to follow tidyverse style guide

NEWS.md, R/unused_import_linter.R, tests/testthat/test-unused_import_linter.R
=> `unused_import_linter()` detects datasets from imports

NEWS.md, R/object_usage_linter.R, tests/testthat/test-object_usage_linter.R
=> object_usage_linter gets correct metadata for infix operators

NEWS.md
To be consistent with the rest of the formatting in the file.
=> Minor header formatting changes for old releases

.github/workflows/R-CMD-check.yaml
=> Add R-CMD-check with non-english locale

R/object_usage_linter.R
=> Move away from //expr XPaths in object_usage_linter

R/string_boundary_linter.R, man/string_boundary_linter.Rd
Part of #1358
Also tidied the wording of the docs which I found confusing on re-read
=> Move away from //expr XPaths in string_boundary_linter

R/package_hooks_linter.R
=> switch away from //expr XPaths in package_hooks_linter

R/any_duplicated_linter.R, R/any_is_na_linter.R, R/conjunct_test_linter.R, R/duplicate_argument_linter.R, R/fixed_regex_linter.R, R/literal_coercion_linter.R, R/outer_negation_linter.R, R/sprintf_linter.R, R/system_file_linter.R
Towards #1358 
Most files have one (or at most two) left, so starting to batch them together
=> Move more XPaths away from //expr logic

.github/workflows/lint-changed-files.yaml, .lintr_new
Also
- Sync up with `lint.yaml` changes
- List linters alphabetically
=> Include more linters in `.lintr_new`

R/expect_comparison_linter.R, R/expect_length_linter.R, R/expect_s3_class_linter.R, R/expect_type_linter.R, R/inner_combine_linter.R, R/missing_package_linter.R, R/pipe_call_linter.R, R/strings_as_factors_linter.R, R/yoda_test_linter.R
=> Another batch of migrations away from //expr

R/T_and_F_symbol_linter.R, R/any_duplicated_linter.R, R/any_is_na_linter.R, R/assignment_linter.R, R/backport_linter.R, R/boolean_arithmetic_linter.R, R/brace_linter.R, R/extraction_operator_linter.R, R/path_linters.R, man/T_and_F_symbol_linter.Rd, man/absolute_path_linter.Rd, man/any_duplicated_linter.Rd, man/any_is_na_linter.Rd, man/assignment_linter.Rd, man/backport_linter.Rd, man/boolean_arithmetic_linter.Rd, man/brace_linter.Rd, man/extraction_operator_linter.Rd, tests/testthat/test-T_and_F_symbol_linter.R, tests/testthat/test-any_is_na_linter.R, tests/testthat/test-boolean_arithmetic_linter.R
=> Add examples to documentation: Part-1 (a-b)

R/infix_spaces_linter.R, R/vector_logic_linter.R
Closes #1608
Currently based against #1610
=> Avoid //* in vector_logic_linter

R/lint.R, tests/testthat/test-sarif_output.R
=> Add a test for `sarif_output()`

R/utils.R, man/get_r_string.Rd
=> add examples to get_r_string

NEWS.md, R/unneeded_concatenation_linter.R, tests/testthat/test-unneeded_concatenation_linter.R
=> don't lint c(...) in unneeded_concatenation_linter(!allow_single_expression)

R/indentation_linter.R, man/indentation_linter.Rd
Just like we are doing in other examples
=> Print the code in `indentation_linter()` examples

.github/workflows/R-CMD-check.yaml, .github/workflows/lint-changed-files.yaml, .github/workflows/lint.yaml, .github/workflows/pkgdown.yaml, .github/workflows/test-coverage.yaml, .github/workflows/test-package-vigilant.yaml
cf. https://github.com/r-lib/actions/commit/cc4293a2b89c8a04e869c75fdb2701035bef502a
=> Sync up GHA workflows with `r-lib/actions`

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml
Catching up with upstream again:
https://github.com/r-lib/actions/blob/d9bf5aba72b8d5f67edc1fab52ea11dcb7fc4ded/examples/check-full.yaml#L30-L31
And minor update to pkgdown workflow
=> Also check on windows R 4.1

DESCRIPTION, vignettes/editors.Rmd
=> Port over `pkgdown::in_pkgdown()`

tests/testthat/test-cache.R, tests/testthat/test-ci.R, tests/testthat/test-rstudio_markers.R
=> Run tests conditionally for `{mockery}`

.github/workflows/check-link-rot.yaml
Inspired by this comment (https://github.com/r-lib/lintr/pull/1690#discussion_r993816614)
=> Add GHA workflow to detect link rot

_pkgdown.yaml
Done using VS Code's formatter.
=> Improve pkgdown YAML formatting

DESCRIPTION
Done via `usethis::use_tidy_description()`
=> Tidy up DESCRIPTION file

R/deprecated.R, R/get_source_expressions.R, R/lintr-deprecated.R
=> Improve deprecation messages for `find_*()`

README.md
Per link-rot CI failure in #1915
=> update codecov badge link

NEWS.md, R/function_left_parentheses_linter.R, tests/testthat/test-function_left_parentheses_linter.R, tests/testthat/test-spaces_left_parentheses_linter.R
Closes #1953
Open to suggestions for avoiding the horrible `range_end_xpath` but I wasn't seeing anything...
=> handle multiline case for function_left_parentheses_linter

NEWS.md, R/function_left_parentheses_linter.R, tests/testthat/test-function_left_parentheses_linter.R
=> fix edge case in function_left_parentheses_linter

NEWS.md, R/lint.R, tests/testthat/test-dir_linters.R, tests/testthat/test-lint_file.R
=> fully deprecate positional arguments in lint()+friends

NEWS.md, R/settings.R, tests/testthat/test-settings.R
=> more informative error message if a lintr config setting is broken

R/paste_linter.R, tests/testthat/test-paste_linter.R
=> catch raw strings in file path inputs

tests/testthat/test-unreachable_code_linter.R
=> use a different # nolint for the test

R/library_call_linter.R, tests/testthat/test-library_call_linter.R
This passes current tests, though I think there's a fair amount of work to do in light of that.
=> Add a test for library_call_linter

R/quotes_linter.R
=> use XPath in quotes_linter.R and drop with()

R/settings.R, R/zzz.R, man/default_settings.Rd, man/read_settings.Rd
I think there's still more we can do, but this is a nice quick improvement
=> Add some more clarity to settings docs

NEWS.md, R/fixed_regex_linter.R, tests/testthat/test-fixed_regex_linter.R
=> pattern= input must be STR_CONST

R/trailing_blank_lines_linter.R
This code always makes me do a double-take.
=> Clarify precedence using parentheses

R/indentation_linter.R, R/keyword_quote_linter.R, R/matrix_apply_linter.R, R/pipe_consistency_linter.R, R/repeat_linter.R, R/settings.R, R/xp_utils.R, man/keyword_quote_linter.Rd, man/pipe_consistency_linter.Rd, man/repeat_linter.Rd
=> Iron out styling inconsistencies

.lintr, R/extract.R, R/line_length_linter.R, tests/testthat/test-linter_tags.R
Since `mapply()` is part of `default_undesirable_functions`.
=> Use `Map()` instead of `mapply()`

R/extract.R
Closes #2211
Decided to inline the function now, but could go either way.
=> use regexpr

NEWS.md
Closes #2223 
Feedback welcome
=> reorganize NEWS

R/condition_message_linter.R, man/condition_message_linter.Rd
=> Fix bad auto-parse by roxygen2

R/backport_linter.R, R/scalar_in_linter.R, R/seq_linter.R, R/xp_utils.R, man/backport_linter.Rd, man/scalar_in_linter.Rd, man/seq_linter.Rd
=> consistent {} notation for packages in docs

NEWS.md, R/unreachable_code_linter.R, tests/testthat/test-unreachable_code_linter.R
=> Fix false positive 'unreachables'

R/exclude.R, R/expect_lint.R, R/extract.R, R/lint.R, R/matrix_apply_linter.R, R/object_usage_linter.R, R/paste_linter.R, R/sort_linter.R, R/sprintf_linter.R, R/utils.R, R/with.R, vignettes/lintr.Rmd
Partial fix for some of the overwrites pointed out in #2307
=> Rename some variables that overwrite base functions

R/addins.R, R/backport_linter.R, R/cache.R, R/comments.R, R/exclude.R, R/expect_lint.R, R/extract.R, R/lint.R, R/linter_tags.R, R/namespace_linter.R, R/object_name_linter.R, R/object_overwrite_linter.R, R/object_usage_linter.R, R/path_utils.R, R/semicolon_linter.R, R/settings.R, R/shared_constants.R, R/tree_utils.R, R/undesirable_function_linter.R, R/undesirable_operator_linter.R, R/use_lintr.R, R/with.R, R/xml_nodes_to_lints.R, R/xp_utils.R, tests/testthat/test-lint.R
=> Add `call. = FALSE` to `warning()` & `stop()` calls

R/unreachable_code_linter.R, tests/testthat/test-unreachable_code_linter.R
=> Move lint to outer expression for if(FALSE) lints in unreachable_code_linter()

R/backport_linter.R
=> Include recent base exports to backport_linter()

NEWS.md
Forgot to remove this when I updated the NEWS in #2357
=> remove dup entry in NEWS

R/unnecessary_placeholder_linter.R
Based against #2459, which was used to verify.
Closes #2479.
=> Comment about '|>' + '_'

.github/CODE_OF_CONDUCT.md, DESCRIPTION, inst/syntastic/lintr.vim, man/lintr-package.Rd
=> Make Michael the new maintainer

NEWS.md
Moves the items from dev to release that are now on CRAN:
https://cran.r-project.org/web/packages/lintr/news/news.html
=> Include patch NEWS entry

NEWS.md, R/zzz.R, man/default_settings.Rd, tests/testthat/test-settings.R
Follow-up on https://github.com/r-lib/lintr/pull/1902/files
More discussion in https://github.com/r-lib/lintr/pull/1558
=> Retire Github comment bot settings and tests

NEWS.md, R/make_linter_from_xpath.R, tests/testthat/test-make_linter_from_xpath.R
Nice to have this error early, currently lazy evaluation hides it until lrun time.
=> Error earlier for missing lint_message

R/addins.R
=> Return an empty list with `<lints>` class in addin

NEWS.md, R/deprecated.R, R/expect_lint.R, R/lint.R, R/paste_linter.R, R/utils.R, man/paste_linter.Rd, tests/testthat/test-lint.R, tests/testthat/test-paste_linter.R
=> Lint for paste0(collapse='') instead of paste(collapse='')

NEWS.md, R/literal_coercion_linter.R, tests/testthat/test-literal_coercion_linter.R
=> Suppress coercion warnings

R/paste_linter.R, tests/testthat/test-paste_linter.R
=> fix paste(collapse='') lints inside pipes

tests/testthat/test-ci.R, tests/testthat/test-settings.R
cf. https://github.com/r-lib/lintr/issues/1692
=> Use public interface to test `logical_env()`

R/utils.R
h/t @AshesITR. One more follow-up to #2603
=> Use deparse1

_pkgdown.yaml
cf. https://pkgdown.r-lib.org/articles/customise.html?q=dark%20#light-switch
=> Allow users to switch between dark and light mode on the website

R/seq_linter.R, man/seq_linter.Rd
=> Update `seq_linter()` docs

R/unnecessary_nesting_linter.R, man/unnecessary_nesting_linter.Rd, tests/testthat/test-unnecessary_nesting_linter.R
=> New branch_exit_calls= argument for unnecessary_nesting_linter

DESCRIPTION, NEWS.md, R/string_boundary_linter.R, tests/testthat/test-string_boundary_linter.R
=> Omit anchor-esque pattern in string_boundary_linter()

NEWS.md, R/seq_linter.R, man/seq_linter.Rd, tests/testthat/test-seq_linter.R
Closes #2577; progress on #2737
=> Recommend seq_along() over seq_len(length(.))

R/matrix_apply_linter.R, man/matrix_apply_linter.Rd
=> Add non-linting examples to ?matrix_apply_linter

R/assignment_linter.R, R/extract.R, R/get_source_expressions.R, R/path_utils.R, R/zzz.R, tests/testthat/test-object_overwrite_linter.R
Follow-up to #2770 -- actually, I lied about it achieving 99.5% :)
Something is wrong with our codecov CI, it doesn't seem to make reports on branches, only on `main`, so I was kind of guessing.
We need 16 more lines to hit 99.5%, this PR will do it.
=> More coverage tests

NEWS.md, R/indentation_linter.R, tests/testthat/test-indentation_linter.R
Closes #2564. Progress on #2737.
I also added some notes about `FOR` to our wiki: https://github.com/r-lib/lintr/wiki/Writing-robust,-performant-linters
=> Improve handling of indentation in `for` loops

NEWS.md, R/unnecessary_nesting_linter.R, tests/testthat/test-unnecessary_nesting_linter.R
=> Give location info about the "parent" IF statement in unnecessary_nesting_linter

.lintr, NEWS.md, R/exclude.R, man/exclude.Rd, man/normalize_exclusions.Rd, tests/testthat/helper.R, tests/testthat/test-lint.R, tests/testthat/test-lint_package.R, tests/testthat/test-normalize_exclusions.R, tests/testthat/test-settings.R
=> Support * (globs) in file/directory exclusions

NEWS.md, R/settings.R, R/utils.R, R/zzz.R, man/default_settings.Rd, tests/testthat/test-settings.R, vignettes/lintr.Rmd
This is vestigial, should have been removed in #2537 but escaped notice
=> Remove GITHUB_TOKEN support

R/nzchar_linter.R, tests/testthat/test-nzchar_linter.R
Closes #2487. Progress on #2737.
=> Add notes about nchar(allowNA=)'s incompatibility with nzchar()

NEWS.md, R/assignment_linter.R, R/implicit_assignment_linter.R, tests/testthat/test-assignment_linter.R
Closes #2765. Progress on #2737
=> Ignore all implicit assignments in assignment_linter("=")

.dev/roxygen_test.R, .github/workflows/repo-meta-tests.yaml
=> Generate the requisite locales for roxygen idempotency test

DESCRIPTION, man/lintr-package.Rd
Since I don't use Twitter anymore.
=> Remove Twitter handle

NEWS.md, R/condition_call_linter.R, tests/testthat/test-condition_call_linter.R
=> Support cases of stop(sprintf( in condition_call_linter

R/object_usage_linter.R
=> Drop safety valve in object_usage_linter
